using System;using System.IO;using System.Collections.Generic;using System.Reflection;using System.Runtime.InteropServices;using System.Threading;using System.Web.Script.Serialization;
class RailPrototype{
[DllImport("ole32.dll",CharSet=CharSet.Unicode,PreserveSig=false)]static extern void CLSIDFromProgID(string p,out Guid g);
[DllImport("oleaut32.dll",PreserveSig=false)]static extern void GetActiveObject(ref Guid g,IntPtr r,[MarshalAs(UnmanagedType.IUnknown)]out object o);
static Assembly api,enums;
static object C(object o,string f,string m,params object[]a){var mi=api.GetType("SolidWorks.Interop.sldworks."+f).GetMethod(m);if(mi==null)throw new Exception("Missing "+f+"."+m);return mi.Invoke(o,a);}
static object G(object o,string f,string p,params object[]a){return api.GetType("SolidWorks.Interop.sldworks."+f).GetProperty(p).GetValue(o,a.Length==0?null:a);}
static void S(object o,string f,string p,object v){api.GetType("SolidWorks.Interop.sldworks."+f).GetProperty(p).SetValue(o,v,null);}
static int E(string t,string v){return Convert.ToInt32(Enum.Parse(enums.GetType("SolidWorks.Interop.swconst."+t),v));}
static void R(bool v,string m){if(!v)throw new Exception(m);}
static Dictionary<string,object> State(object d){return new Dictionary<string,object>{{"path",C(d,"IModelDoc2","GetPathName")},{"dirty",C(d,"IModelDoc2","GetSaveFlag")}};}
static void Line(object sm,List<object>segs,double x1,double y1,double x2,double y2){object s=C(sm,"ISketchManager","CreateLine",x1,y1,0d,x2,y2,0d);R(s!=null,"Line failed");segs.Add(s);}
static void Arc(object sm,List<object>segs,double x1,double y1,double x2,double y2,double xm,double ym){object s=C(sm,"ISketchManager","Create3PointArc",x1,y1,0d,x2,y2,0d,xm,ym,0d);R(s!=null,"Arc failed");segs.Add(s);}
static void RR(object sm,List<object>segs,double cx,double bw,double h,double r){double l=cx-bw/2,rt=cx+bw/2,bt=-h/2,tp=h/2,k=r/Math.Sqrt(2);
Line(sm,segs,l+r,bt,rt-r,bt);Arc(sm,segs,rt-r,bt,rt,bt+r,rt-r+k,bt+r-k);
Line(sm,segs,rt,bt+r,rt,tp-r);Arc(sm,segs,rt,tp-r,rt-r,tp,rt-r+k,tp-r+k);
Line(sm,segs,rt-r,tp,l+r,tp);Arc(sm,segs,l+r,tp,l,tp-r,l+r-k,tp-r+k);
Line(sm,segs,l,tp-r,l,bt+r);Arc(sm,segs,l,bt+r,l+r,bt,l+r-k,bt+r-k);}
static double Volume(object d){object bs=C(d,"IPartDoc","GetBodies2",0,false);R(bs!=null&&((Array)bs).Length==2,"Expected 2 solid bodies");double v=0;foreach(object body in (Array)bs){object raw=C(body,"IBody2","GetMassProperties",7850d);double[] mp=(double[])raw;v+=mp[3];}return v;}
[STAThread]static int Main(string[]args){object app=null,doc=null,previous=null;string prevTitle=null,newTitle=null;bool saved=false;var report=new Dictionary<string,object>();using(var mx=new Mutex(false,"Global\\SolidWorksCodex_COM_Mutex")){bool held=false;try{
held=mx.WaitOne(10000);R(held,"Connector busy");api=Assembly.LoadFrom(@"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.sldworks.dll");enums=Assembly.LoadFrom(@"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.swconst.dll");Guid clsid;CLSIDFromProgID("SldWorks.Application",out clsid);GetActiveObject(ref clsid,IntPtr.Zero,out app);previous=G(app,"ISldWorks","IActiveDoc2");if(previous!=null){prevTitle=Convert.ToString(C(previous,"IModelDoc2","GetTitle"));report["previous_before"]=State(previous);}
string output=Path.GetFullPath(args[0]);R(output.StartsWith(@"C:\Users\adm\Documents\Codex\2026-10-04\new-chat-2\outputs\",StringComparison.OrdinalIgnoreCase)&&!File.Exists(output),"Invalid destination");
doc=C(app,"ISldWorks","NewDocument",@"C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2026\templates\gost-part.prtdot",0,0d,0d);R(doc!=null,"New part failed");newTitle=Convert.ToString(C(doc,"IModelDoc2","GetTitle"));object plane=C(doc,"IModelDoc2","FirstFeature");while(plane!=null&&Convert.ToString(C(plane,"IFeature","GetTypeName2"))!="RefPlane")plane=C(plane,"IFeature","GetNextFeature");R(plane!=null,"No plane");C(doc,"IModelDoc2","ClearSelection2",true);C(plane,"IFeature","Select2",false,0);object sm=G(doc,"IModelDoc2","SketchManager");C(sm,"ISketchManager","InsertSketch",true);var segments=new List<object>();S(sm,"ISketchManager","AddToDB",true);foreach(double cx in new double[]{-.3,.3}){RR(sm,segments,cx,.05,.1,.006);RR(sm,segments,cx,.044,.094,.003);}
S(sm,"ISketchManager","AddToDB",false);C(doc,"IModelDoc2","ClearSelection2",true);bool add=false;foreach(object s in segments){R(Convert.ToBoolean(C(s,"ISketchSegment","Select4",add,null)),"Fix selection failed");add=true;}C(doc,"IModelDoc2","SketchAddConstraints","sgFIXED");C(doc,"IModelDoc2","ClearSelection2",true);C(sm,"ISketchManager","InsertSketch",true);object sketch=C(doc,"IModelDoc2","FeatureByPositionReverse",0);S(sketch,"IFeature","Name","PROFILE_100_50_3_R6_FIXED");C(sketch,"IFeature","Select2",false,0);object fm=G(doc,"IModelDoc2","FeatureManager");object boss=C(fm,"IFeatureManager","FeatureExtrusion3",true,false,false,0,0,5d,0d,false,false,false,false,0d,0d,false,false,false,false,false,false,true,0,0d,false);R(boss!=null,"Extrusion failed");S(boss,"IFeature","Name","TWO_RAILS_PROTOTYPE");
object dd=C(boss,"IFeature","GetFirstDisplayDimension");R(dd!=null,"Depth dimension missing");object dim=C(dd,"IDisplayDimension","GetDimension2",0);S(dim,"IDimension","Name","AI_L_MODULE");object eq=C(doc,"IModelDoc2","GetEquationMgr");R(Convert.ToInt32(C(eq,"IEquationMgr","Add2",-1,"\"L_MODULE\" = 5000",false))>=0,"Global variable failed");R(Convert.ToInt32(C(eq,"IEquationMgr","Add2",-1,"\""+G(dim,"IDimension","FullName")+"\" = \"L_MODULE\"",false))>=0,"Dimension equation failed");C(eq,"IEquationMgr","EvaluateAll");R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Rebuild failed");double area=840.8230016469242e-6,expected=area*5*2;double vol=Volume(doc);R(Math.Abs(vol-expected)<1e-8,"Volume differs from analytical rounded section");report["initial_volume_m3"]=vol;report["calculated_mass_kg_at_7850"]=vol*7850;
api.GetType("SolidWorks.Interop.sldworks.IEquationMgr").GetProperty("Equation").SetValue(eq,"\"L_MODULE\" = 4500",new object[]{0});C(eq,"IEquationMgr","EvaluateAll");R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Length probe failed");R(Math.Abs(Volume(doc)-area*4.5*2)<1e-8,"Length probe volume failed");api.GetType("SolidWorks.Interop.sldworks.IEquationMgr").GetProperty("Equation").SetValue(eq,"\"L_MODULE\" = 5000",new object[]{0});C(eq,"IEquationMgr","EvaluateAll");R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false))&&Math.Abs(Volume(doc)-expected)<1e-8,"Restoration failed");
object ext=G(doc,"IModelDoc2","Extension");object prop=G(ext,"IModelDocExtension","CustomPropertyManager","");int type=E("swCustomInfoType_e","swCustomInfoText"),replace=E("swCustomPropertyAddOption_e","swCustomPropertyReplaceValue");C(prop,"ICustomPropertyManager","Add3","STATUS",type,"PRELIMINARY STRUCTURAL PROTOTYPE - NOT FOR MANUFACTURING",replace);C(prop,"ICustomPropertyManager","Add3","REVISION",type,"R03",replace);C(prop,"ICustomPropertyManager","Add3","SCOPE",type,"Two rounded hollow rails, 100x50x3, R6/R3, centre spacing 600, L5000. Section fixed; only length equation-driven. No welds, supports, crossmembers, rollers or belt tension loads.",replace);C(prop,"ICustomPropertyManager","Add3","MATERIAL",type,"St3 per brief; subgrade not selected. Mass verified using explicit density 7850 kg/m3, not assigned material.",replace);C(doc,"IModelDoc2","ShowNamedView2","*Isometric",7);C(doc,"IModelDoc2","ViewZoomtofit2");object[] saveArgs={output,0,1,null,null,0,0};R(Convert.ToBoolean(C(ext,"IModelDocExtension","SaveAs3",saveArgs))&&Convert.ToInt32(saveArgs[5])==0&&File.Exists(output),"Save failed");saved=true;
string title=Convert.ToString(C(doc,"IModelDoc2","GetTitle"));C(app,"ISldWorks","CloseDoc",title);object[] openArgs={output,1,1,"",0,0};doc=C(app,"ISldWorks","OpenDoc6",openArgs);R(doc!=null&&Convert.ToInt32(openArgs[4])==0,"Reopen failed");R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false))&&Math.Abs(Volume(doc)-expected)<1e-8,"Reopen geometry failed");object[] saveFinal={1,0,0};R(Convert.ToBoolean(C(doc,"IModelDoc2","Save3",saveFinal))&&Convert.ToInt32(saveFinal[1])==0,"Final save failed");report["path"]=output;report["solid_body_count"]=2;report["length_probe_4500_and_restored_5000"]=true;report["reopened_rebuild_and_volume_checked"]=true;report["save_errors"]=saveArgs[5];report["save_warnings"]=saveArgs[6];report["material_assigned"]=false;report["manufacturing_approved"]=false;report["section_shape_fixed_not_dimension_driven"]=true;report["ok"]=true;
}catch(Exception ex){report["ok"]=false;report["error"]=ex.ToString();if(doc!=null&&!saved&&newTitle!=null)try{C(app,"ISldWorks","CloseDoc",newTitle);}catch{}}
finally{if(previous!=null&&prevTitle!=null)try{report["previous_after"]=State(previous);object[] act={prevTitle,true,0};C(app,"ISldWorks","ActivateDoc2",act);}catch{}if(held)mx.ReleaseMutex();}}string json=new JavaScriptSerializer().Serialize(report);File.WriteAllText(args[1],json,new System.Text.UTF8Encoding(false));Console.WriteLine(json);return report.ContainsKey("ok")&&(bool)report["ok"]?0:1;}
}
