using System;using System.Runtime.InteropServices.ComTypes;using System.IO;using System.Collections.Generic;using System.Reflection;using System.Runtime.InteropServices;using System.Threading;using System.Web.Script.Serialization;
class FlatR11{
[DllImport("ole32.dll",CharSet=CharSet.Unicode,PreserveSig=false)]static extern void CLSIDFromProgID(string p,out Guid g);
[DllImport("oleaut32.dll",PreserveSig=false)]static extern void GetActiveObject(ref Guid g,IntPtr r,[MarshalAs(UnmanagedType.IUnknown)]out object o);
[DllImport("ole32.dll")]static extern int GetRunningObjectTable(int reserved,out IRunningObjectTable rot);[DllImport("ole32.dll")]static extern int CreateBindCtx(int reserved,out IBindCtx ctx);
static object AppAtPID(string pid){for(int k=0;k<60;k++){IRunningObjectTable rot;GetRunningObjectTable(0,out rot);IEnumMoniker en;rot.EnumRunning(out en);IMoniker[]ms=new IMoniker[1];while(en.Next(1,ms,IntPtr.Zero)==0){IBindCtx ctx;CreateBindCtx(0,out ctx);string name;ms[0].GetDisplayName(ctx,null,out name);if(name=="SolidWorks_PID_"+pid){object raw;rot.GetObject(ms[0],out raw);return Marshal.CreateWrapperOfType(raw,api.GetType("SolidWorks.Interop.sldworks.SldWorksClass"));}}Thread.Sleep(500);}throw new Exception("Own PID did not register in ROT");}
static Assembly api,enums;
static object C(object o,string f,string m,params object[]a){var mi=api.GetType("SolidWorks.Interop.sldworks."+f).GetMethod(m);if(mi==null)throw new Exception("Missing "+f+"."+m);return mi.Invoke(o,a);}
static object G(object o,string f,string p,params object[]a){return api.GetType("SolidWorks.Interop.sldworks."+f).GetProperty(p).GetValue(o,a.Length==0?null:a);}
static void S(object o,string f,string p,object v){api.GetType("SolidWorks.Interop.sldworks."+f).GetProperty(p).SetValue(o,v,null);}
static int E(string t,string v){return Convert.ToInt32(Enum.Parse(enums.GetType("SolidWorks.Interop.swconst."+t),v));}
static void R(bool v,string m){if(!v)throw new Exception(m);}
static Dictionary<string,object> State(object d){return new Dictionary<string,object>{{"path",C(d,"IModelDoc2","GetPathName")},{"dirty",C(d,"IModelDoc2","GetSaveFlag")}};}
static void Line(object sm,List<object>segs,double x1,double y1,double x2,double y2){object s=C(sm,"ISketchManager","CreateLine",x1,y1,0d,x2,y2,0d);R(s!=null,"Line failed");segs.Add(s);}
static void Arc(object sm,List<object>segs,double x1,double y1,double x2,double y2,double xm,double ym){object s=C(sm,"ISketchManager","Create3PointArc",x1,y1,0d,x2,y2,0d,xm,ym,0d);R(s!=null,"Arc failed");segs.Add(s);}
static void RR(object sm,List<object>segs,double cx,double cy,double bw,double h,double r){double l=cx-bw/2,rt=cx+bw/2,bt=cy-h/2,tp=cy+h/2,k=r/Math.Sqrt(2);
Line(sm,segs,l+r,bt,rt-r,bt);Arc(sm,segs,rt-r,bt,rt,bt+r,rt-r+k,bt+r-k);
Line(sm,segs,rt,bt+r,rt,tp-r);Arc(sm,segs,rt,tp-r,rt-r,tp,rt-r+k,tp-r+k);
Line(sm,segs,rt-r,tp,l+r,tp);Arc(sm,segs,l+r,tp,l,tp-r,l+r-k,tp-r+k);
Line(sm,segs,l,tp-r,l,bt+r);Arc(sm,segs,l,bt+r,l+r,bt,l+r-k,bt+r-k);}

static double[] Point(object app,object tr,double x,double y,double z){object mu=C(app,"ISldWorks","GetMathUtility");object p=C(mu,"IMathUtility","CreatePoint",new object[]{new double[]{x,y,z}});return (double[])G(C(p,"IMathPoint","MultiplyTransform",tr),"IMathPoint","ArrayData");}
static object Finish(object app,object doc,object sm,object tr,List<object> segs,int axis,double depth,double start,string name,bool merge=false){
S(sm,"ISketchManager","AddToDB",false);C(doc,"IModelDoc2","ClearSelection2",true);bool add=false;foreach(object sg in segs){R(Convert.ToBoolean(C(sg,"ISketchSegment","Select4",add,null)),"Fix selection failed");add=true;}C(doc,"IModelDoc2","SketchAddConstraints","sgFIXED");C(doc,"IModelDoc2","ClearSelection2",true);
object inv=C(tr,"IMathTransform","Inverse");double[] p0=Point(app,inv,0,0,0),pn=Point(app,inv,0,0,1);double normal=pn[axis]-p0[axis];R(Math.Abs(Math.Abs(normal)-1)<1e-8,"Unexpected normal");C(sm,"ISketchManager","InsertSketch",true);object sf=C(doc,"IModelDoc2","FeatureByPositionReverse",0);S(sf,"IFeature","Name",name+"_PROFILE");C(sf,"IFeature","Select2",false,0);object fm=G(doc,"IModelDoc2","FeatureManager");object boss=C(fm,"IFeatureManager","FeatureExtrusion3",true,false,normal<0,0,0,depth,0d,false,false,false,false,0d,0d,false,false,false,false,merge,false,true,start==0?0:E("swStartConditions_e","swStartOffset"),Math.Abs(start),start*normal<0);R(boss!=null,"Extrusion failed "+name);S(boss,"IFeature","Name",name);object[] faces=(object[])C(boss,"IFeature","GetFaces");R(faces.Length>0,"No faces");object body=C(faces[0],"IFace2","GetBody");S(body,"IBody2","Name",name);return body;
}
static object Tube(object app,object doc,object plane,int axis,double cx,double cy,double cz,double w,double h,double t,double r,double depth,double start,string name){
C(doc,"IModelDoc2","ClearSelection2",true);R(Convert.ToBoolean(C(plane,"IFeature","Select2",false,0)),"Plane select");object sm=G(doc,"IModelDoc2","SketchManager");C(sm,"ISketchManager","InsertSketch",true);object sk=G(sm,"ISketchManager","ActiveSketch"),tr=G(sk,"ISketch","ModelToSketchTransform");double[] q=Point(app,tr,cx,cy,cz);var segs=new List<object>();S(sm,"ISketchManager","AddToDB",true);
if(t>0){RR(sm,segs,q[0],q[1],w,h,r);RR(sm,segs,q[0],q[1],w-2*t,h-2*t,r-t);}else{Line(sm,segs,q[0]-w/2,q[1]-h/2,q[0]+w/2,q[1]-h/2);Line(sm,segs,q[0]+w/2,q[1]-h/2,q[0]+w/2,q[1]+h/2);Line(sm,segs,q[0]+w/2,q[1]+h/2,q[0]-w/2,q[1]+h/2);Line(sm,segs,q[0]-w/2,q[1]+h/2,q[0]-w/2,q[1]-h/2);}
return Finish(app,doc,sm,tr,segs,axis,depth,start,name);
}
static void Wedge(object app,object doc,object plane,double z,double a,double tc,string name){
C(doc,"IModelDoc2","ClearSelection2",true);C(plane,"IFeature","Select2",false,0);object sm=G(doc,"IModelDoc2","SketchManager");C(sm,"ISketchManager","InsertSketch",true);object tr=G(G(sm,"ISketchManager","ActiveSketch"),"ISketch","ModelToSketchTransform");var segs=new List<object>();S(sm,"ISketchManager","AddToDB",true);
double[,] pts={{-.05,.04-tc},{.05,.04-tc},{.05,.04-.05*Math.Tan(a)},{-.05,.04+.05*Math.Tan(a)}};for(int i=0;i<4;i++){int j=(i+1)%4;double[] p=Point(app,tr,pts[i,0],pts[i,1],0),q=Point(app,tr,pts[j,0],pts[j,1],0);Line(sm,segs,p[0],p[1],q[0],q[1]);}foreach(double x in new double[]{-.030,.030}) Circle(app,sm,tr,segs,x,.04-tc+.012,0,.00525);Finish(app,doc,sm,tr,segs,2,.080,z-.040,name);
}

static void Circle(object app,object sm,object tr,List<object>seg,double x,double y,double z,double r){double[]q=Point(app,tr,x,y,z);object c=C(sm,"ISketchManager","CreateCircleByRadius",q[0],q[1],0d,r);R(c!=null,"Circle failed");seg.Add(c);}
static void Slot(object app,object sm,object tr,List<object>seg,double x,double y,double length,double height){double[]q=Point(app,tr,x,y,0);double dx=(length-height)/2,r=height/2;Line(sm,seg,q[0]-dx,q[1]-r,q[0]+dx,q[1]-r);Arc(sm,seg,q[0]+dx,q[1]-r,q[0]+dx,q[1]+r,q[0]+dx+r,q[1]);Line(sm,seg,q[0]+dx,q[1]+r,q[0]-dx,q[1]+r);Arc(sm,seg,q[0]-dx,q[1]+r,q[0]-dx,q[1]-r,q[0]-dx-r,q[1]);}
static object Begin(object doc,object plane,out object sm,out object tr){C(doc,"IModelDoc2","ClearSelection2",true);C(plane,"IFeature","Select2",false,0);sm=G(doc,"IModelDoc2","SketchManager");C(sm,"ISketchManager","InsertSketch",true);tr=G(G(sm,"ISketchManager","ActiveSketch"),"ISketch","ModelToSketchTransform");S(sm,"ISketchManager","AddToDB",true);return sm;}
static void Guide(object app,object doc,object plane,double z,double a,double tc,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();double y=.04-tc;double[]q=Point(app,tr,0,y+.05,0);Line(sm,seg,q[0]-.08,q[1]-.05,q[0]+.08,q[1]-.05);Line(sm,seg,q[0]+.08,q[1]-.05,q[0]+.08,q[1]+.05);Line(sm,seg,q[0]+.08,q[1]+.05,q[0]-.08,q[1]+.05);Line(sm,seg,q[0]-.08,q[1]+.05,q[0]-.08,q[1]-.05);foreach(double x in new double[]{-.03,.03})Circle(app,sm,tr,seg,x,y+.012,0,.00525);Circle(app,sm,tr,seg,-.035,.04+.05/Math.Cos(a)+.035*Math.Tan(a),0,.0105);Slot(app,sm,tr,seg,.035,.04+.05/Math.Cos(a)-.035*Math.Tan(a),.033,.021);Finish(app,doc,sm,tr,seg,2,.006,z-.003,name);}
static void Ring(object app,object doc,object plane,double x,double y,double od,double id,double length,double start,string name,bool merge=false){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();Circle(app,sm,tr,seg,x,y,0,od/2);if(id>0)Circle(app,sm,tr,seg,x,y,0,id/2);Finish(app,doc,sm,tr,seg,2,length,start,name,merge);}
static void Hex(object app,object doc,object plane,double x,double y,double af,double id,double length,double start,string name,bool merge=false){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();double[]q=Point(app,tr,x,y,0);double r=af/Math.Sqrt(3);for(int j=0;j<6;j++){double a=j*Math.PI/3,b=(j+1)*Math.PI/3;Line(sm,seg,q[0]+r*Math.Cos(a),q[1]+r*Math.Sin(a),q[0]+r*Math.Cos(b),q[1]+r*Math.Sin(b));}if(id>0)Circle(app,sm,tr,seg,x,y,0,id/2);Finish(app,doc,sm,tr,seg,2,length,start,name,merge);}
static void Fastener(object app,object doc,object plane,double x,double y,double z,double d,double od,double id,double boltlen,double af,double hh,double nh,double wd,string name){Ring(app,doc,plane,x,y,od,id,.097,z-.0485,"SLEEVE_"+name);Ring(app,doc,plane,x,y,d,0,boltlen,z-.0505,"SHAFT_"+name);Hex(app,doc,plane,x,y,af,0,hh,z-.0505-hh,"HEAD_"+name);Hex(app,doc,plane,x,y,af,d,nh,z+.0505,"NUT_"+name);foreach(double dz in new double[]{-.0495,.0495})Ring(app,doc,plane,x,y,wd,id,.002,z+dz-.001,"WASHER_"+name+(dz<0?"_MINUS":"_PLUS"));}
static void CutRail(object app,object doc,object plane,double x,double y,double start,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();Circle(app,sm,tr,seg,x,y,0,.01025);S(sm,"ISketchManager","AddToDB",false);C(doc,"IModelDoc2","ClearSelection2",true);foreach(object sg in seg)C(sg,"ISketchSegment","Select4",true,null);C(doc,"IModelDoc2","SketchAddConstraints","sgFIXED");C(doc,"IModelDoc2","ClearSelection2",true);object inv=C(tr,"IMathTransform","Inverse");double[]p0=Point(app,inv,0,0,0),pn=Point(app,inv,0,0,1);double normal=pn[2]-p0[2];C(sm,"ISketchManager","InsertSketch",true);object sf=C(doc,"IModelDoc2","FeatureByPositionReverse",0);S(sf,"IFeature","Name",name+"_PROFILE");C(sf,"IFeature","Select2",false,0);object cut=C(G(doc,"IModelDoc2","FeatureManager"),"IFeatureManager","FeatureCut3",true,false,normal>0,0,0,.050,0d,false,false,false,false,0d,0d,false,false,false,false,false,false,true,false,false,false,E("swStartConditions_e","swStartOffset"),Math.Abs(start),start*normal<0);R(cut!=null,"Rail cut failed "+name);S(cut,"IFeature","Name",name);}

static List<object> Data(object doc){var data=new List<object>();foreach(object body in (Array)C(doc,"IPartDoc","GetBodies2",0,false)){double[] mp=(double[])C(body,"IBody2","GetMassProperties",7850d);var planes=new List<object>();foreach(object f in (Array)C(body,"IBody2","GetFaces")){object surf=C(f,"IFace2","GetSurface");if(Convert.ToBoolean(C(surf,"ISurface","IsPlane")))planes.Add(new Dictionary<string,object>{{"plane",G(surf,"ISurface","PlaneParams")},{"area_m2",C(f,"IFace2","GetArea")}});}data.Add(new Dictionary<string,object>{{"name",G(body,"IBody2","Name")},{"volume_m3",mp[3]},{"centroid_m",new double[]{mp[0],mp[1],mp[2]}},{"planes",planes}});}return data;}
static double Volume(object doc){double v=0;foreach(object b in (Array)C(doc,"IPartDoc","GetBodies2",0,false))v+=((double[])C(b,"IBody2","GetMassProperties",7850d))[3];return v;}
static List<object> Interferences(object doc){return Interferences(doc,null,0d);}static List<object> Interferences(object doc,object app,double dx){object[] bs=(object[])C(doc,"IPartDoc","GetBodies2",0,false);if(dx!=0){object mu=C(app,"ISldWorks","GetMathUtility");object tr=C(mu,"IMathUtility","CreateTransform",new object[]{new double[]{1,0,0,0,1,0,0,0,1,dx,-dx*Math.Tan(1.5*Math.PI/180),0,1,0,0,0}});for(int k=0;k<bs.Length;k++){string name=Convert.ToString(G(bs[k],"IBody2","Name"));object copy=C(bs[k],"IBody2","Copy");S(copy,"IBody2","Name",name);if(name.Contains("MODULE_OUT")||name.StartsWith("RAIL_HOLE_")&&name.EndsWith("_OUT"))R(Convert.ToBoolean(C(copy,"IBody2","ApplyTransform",tr)),"Stroke transform failed");bs[k]=copy;}}var data=new List<object>();for(int i=0;i<bs.Length;i++)for(int j=i+1;j<bs.Length;j++){object a=C(bs[i],"IBody2","Copy"),b=C(bs[j],"IBody2","Copy");object[] args={E("swBodyOperationType_e","SWBODYINTERSECT"),b,0};object raw=C(a,"IBody2","Operations2",args);double v=0;if(raw is Array)foreach(object rb in (Array)raw){double[] mp=(double[])C(rb,"IBody2","GetMassProperties",7850d);v+=mp[3];}int error=Convert.ToInt32(args[2]);R(error==0||error==5||error==6||error==1067,"Unresolved boolean error "+error);R(v<1e-10,"Interference: "+G(bs[i],"IBody2","Name")+" / "+G(bs[j],"IBody2","Name")+" v="+v);data.Add(new Dictionary<string,object>{{"a",G(bs[i],"IBody2","Name")},{"b",G(bs[j],"IBody2","Name")},{"volume_m3",v},{"api_code",error}});}return data;}

static void Fork(object app,object doc,object plane,double x,double z,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();double[,] pts={{x-.030,.100},{x+.030,.100},{x+.030,.145},{x+.0125,.145},{x+.0125,.124}};
for(int j=0;j<4;j++){double[]p=Point(app,tr,pts[j,0],pts[j,1],0),q=Point(app,tr,pts[j+1,0],pts[j+1,1],0);Line(sm,seg,p[0],p[1],q[0],q[1]);}
double[]p1=Point(app,tr,x+.0125,.124,0),p2=Point(app,tr,x-.0125,.124,0),pm=Point(app,tr,x,.1115,0);Arc(sm,seg,p1[0],p1[1],p2[0],p2[1],pm[0],pm[1]);
double[,] rest={{x-.0125,.124},{x-.0125,.145},{x-.030,.145},{x-.030,.100}};for(int j=0;j<3;j++){double[]p=Point(app,tr,rest[j,0],rest[j,1],0),q=Point(app,tr,rest[j+1,0],rest[j+1,1],0);Line(sm,seg,p[0],p[1],q[0],q[1]);}Finish(app,doc,sm,tr,seg,2,.008,z-.004,name);}
static void Rotate(object app,object doc,object body,double a){string name=Convert.ToString(G(body,"IBody2","Name"));C(doc,"IModelDoc2","ClearSelection2",true);object sd=C(G(doc,"IModelDoc2","SelectionManager"),"ISelectionMgr","CreateSelectData");S(sd,"ISelectData","Mark",1);R(Convert.ToBoolean(C(body,"IBody2","Select2",false,sd)),"Body select");object mv=C(G(doc,"IModelDoc2","FeatureManager"),"IFeatureManager","InsertMoveCopyBody2",0d,0d,0d,0d,0d,0d,0d,0d,0d,-a,false,0);R(mv!=null,"Move failed");S(mv,"IFeature","Name",name+"_SLOPE");object def=C(mv,"IFeature","GetDefinition");R(Convert.ToBoolean(C(def,"IMoveCopyBodyFeatureData","AccessSelections",doc,null)),"Move access");S(def,"IMoveCopyBodyFeatureData","TransformType",E("swMoveCopyBodyFeatureTransformType_e","swTransformType_Rotation"));S(def,"IMoveCopyBodyFeatureData","TransformReferenceEntity",null);S(def,"IMoveCopyBodyFeatureData","RotationOriginX",0d);S(def,"IMoveCopyBodyFeatureData","RotationOriginY",0d);S(def,"IMoveCopyBodyFeatureData","RotationOriginZ",0d);S(def,"IMoveCopyBodyFeatureData","TransformX",0d);S(def,"IMoveCopyBodyFeatureData","TransformY",0d);S(def,"IMoveCopyBodyFeatureData","TransformZ",-a);R(Convert.ToBoolean(C(mv,"IFeature","ModifyDefinition",def,doc,null)),"Move update");}

static void RectSeg(object app,object sm,object tr,List<object>segs,double x1,double y1,double x2,double y2){double[,]pp={{x1,y1},{x2,y1},{x2,y2},{x1,y2}};for(int j=0;j<4;j++){double[]p=Point(app,tr,pp[j,0],pp[j,1],0),q=Point(app,tr,pp[(j+1)%4,0],pp[(j+1)%4,1],0);Line(sm,segs,p[0],p[1],q[0],q[1]);}}
static void FlatCircle(object app,object sm,object tr,List<object>segs,double a,double r,double yc){double b=Math.Sqrt(r*r-a*a);double[,]pp={{a,yc+b},{a,yc-b},{-a,yc-b},{-a,yc+b}};double[]p=Point(app,tr,pp[0,0],pp[0,1],0),q=Point(app,tr,pp[1,0],pp[1,1],0);Line(sm,segs,p[0],p[1],q[0],q[1]);p=q;q=Point(app,tr,-a,yc-b,0);double[]m=Point(app,tr,0,yc-r,0);Arc(sm,segs,p[0],p[1],q[0],q[1],m[0],m[1]);p=q;q=Point(app,tr,-a,yc+b,0);Line(sm,segs,p[0],p[1],q[0],q[1]);p=q;q=Point(app,tr,a,yc+b,0);m=Point(app,tr,0,yc+r,0);Arc(sm,segs,p[0],p[1],q[0],q[1],m[0],m[1]);}
static void CutProfile(object app,object doc,object sm,object tr,List<object>seg,int axis,double start,double depth,string name){S(sm,"ISketchManager","AddToDB",false);C(doc,"IModelDoc2","ClearSelection2",true);foreach(object sg in seg)C(sg,"ISketchSegment","Select4",true,null);C(doc,"IModelDoc2","SketchAddConstraints","sgFIXED");C(doc,"IModelDoc2","ClearSelection2",true);object inv=C(tr,"IMathTransform","Inverse");double[]p0=Point(app,inv,0,0,0),pn=Point(app,inv,0,0,1);double normal=pn[axis]-p0[axis];C(sm,"ISketchManager","InsertSketch",true);object sf=C(doc,"IModelDoc2","FeatureByPositionReverse",0);S(sf,"IFeature","Name",name+"_PROFILE");C(sf,"IFeature","Select2",false,0);object cut=C(G(doc,"IModelDoc2","FeatureManager"),"IFeatureManager","FeatureCut3",true,false,normal>0,0,0,depth,0d,false,false,false,false,0d,0d,false,false,false,false,false,false,true,false,false,false,E("swStartConditions_e","swStartOffset"),Math.Abs(start),start*normal<0);R(cut!=null,"Cut failed "+name);S(cut,"IFeature","Name",name);object[]ff=(object[])C(cut,"IFeature","GetFaces");S(C(ff[0],"IFace2","GetBody"),"IBody2","Name",name.StartsWith("SHAFT")?"SHAFT":name.Contains("LEFT")?"STATOR_LEFT":"STATOR_RIGHT");}
static void ShaftFlat(object app,object doc,object plane,double start,double side,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();RectSeg(app,sm,tr,seg,side>0?.010:-.020,.110,side>0?.020:-.010,.138);CutProfile(app,doc,sm,tr,seg,2,start,.024,name);}
static void StatorHole(object app,object doc,object plane,double z,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();Circle(app,sm,tr,seg,0,.124,z,.00215);CutProfile(app,doc,sm,tr,seg,0,.0125,.006,name);}
static void Keeper(object app,object doc,object plane,double start,double depth,bool bore,bool merge,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();RectSeg(app,sm,tr,seg,-.030,.100,.030,.145);foreach(double x in new double[]{-.022,.022})Circle(app,sm,tr,seg,x,.135,0,.00325);if(bore)FlatCircle(app,sm,tr,seg,.01025,.0128,.12425);Finish(app,doc,sm,tr,seg,2,depth,start,name,merge);}
static void NewFork(object app,object doc,object plane,double z,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();double a=.01025,r=.01275,y=.12425,b=Math.Sqrt(r*r-a*a);double[,]pp={{-.030,.100},{.030,.100},{.030,.145},{a,.145},{a,y-b}};for(int j=0;j<4;j++){double[]p=Point(app,tr,pp[j,0],pp[j,1],0),q=Point(app,tr,pp[j+1,0],pp[j+1,1],0);Line(sm,seg,p[0],p[1],q[0],q[1]);}double[]p1=Point(app,tr,a,y-b,0),p2=Point(app,tr,-a,y-b,0),m=Point(app,tr,0,y-r,0);Arc(sm,seg,p1[0],p1[1],p2[0],p2[1],m[0],m[1]);double[,]rr={{-a,y-b},{-a,.145},{-.030,.145},{-.030,.100}};for(int j=0;j<3;j++){double[]p=Point(app,tr,rr[j,0],rr[j,1],0),q=Point(app,tr,rr[j+1,0],rr[j+1,1],0);Line(sm,seg,p[0],p[1],q[0],q[1]);}foreach(double x in new double[]{-.022,.022})Circle(app,sm,tr,seg,x,.135,0,.00325);Finish(app,doc,sm,tr,seg,2,.008,z-.004,name);}
static double Z(double z,bool right){return right?.7-z:z;}
static void RMirror(object app,object doc,object plane,double od,double id,double length,double start,bool right,string name,bool merge){Ring(app,doc,plane,0,.124,od,id,length,right?.7-start-length:start,name,merge);}
static List<object> ServiceInterferences(object doc,object app){var kept=new List<object>();foreach(object b in (Array)C(doc,"IPartDoc","GetBodies2",0,false)){string n=Convert.ToString(G(b,"IBody2","Name"));if(n.StartsWith("M6_"))continue;object copy=C(b,"IBody2","Copy");S(copy,"IBody2","Name",n);double dz=0,dy=0;if(n.StartsWith("KEEPER_"))dz=n.Contains("LEFT")?-.015:.015;else if(!n.StartsWith("REF_")&&!n.StartsWith("FORK_"))dy=.035;double a=1.5*Math.PI/180;object mu=C(app,"ISldWorks","GetMathUtility");object tr=C(mu,"IMathUtility","CreateTransform",new object[]{new double[]{1,0,0,0,1,0,0,0,1,dy*Math.Sin(a),dy*Math.Cos(a),dz,1,0,0,0}});R(Convert.ToBoolean(C(copy,"IBody2","ApplyTransform",tr)),"Service move");kept.Add(copy);}return PairCheck(kept.ToArray());}
static List<object> PairCheck(object[]bs){var rr=new List<object>();for(int i=0;i<bs.Length;i++)for(int j=i+1;j<bs.Length;j++){object a=C(bs[i],"IBody2","Copy"),b=C(bs[j],"IBody2","Copy");object[]ar={E("swBodyOperationType_e","SWBODYINTERSECT"),b,0};object raw=C(a,"IBody2","Operations2",ar);double v=0;if(raw is Array)foreach(object rb in (Array)raw)v+=((double[])C(rb,"IBody2","GetMassProperties",7850d))[3];int err=Convert.ToInt32(ar[2]);R(err==0||err==5||err==6||err==1067,"Service Boolean error");R(v<1e-10,"Service interference "+G(bs[i],"IBody2","Name")+" / "+G(bs[j],"IBody2","Name"));rr.Add(new Dictionary<string,object>{{"a",G(bs[i],"IBody2","Name")},{"b",G(bs[j],"IBody2","Name")},{"volume_m3",v}});}return rr;}
static object Build(object app){object doc=C(app,"ISldWorks","NewDocument",@"C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2026\templates\gost-part.prtdot",0,0d,0d);R(doc!=null,"New part");var pls=new List<object>();object f=C(doc,"IModelDoc2","FirstFeature");while(f!=null){if(Convert.ToString(C(f,"IFeature","GetTypeName2"))=="RefPlane")pls.Add(f);f=C(f,"IFeature","GetNextFeature");}
Ring(app,doc,pls[0],0,.124,.025,0,.620,.040,"SHAFT");int k=0;foreach(double start in new double[]{.040,.636})foreach(double side in new double[]{-1,1})ShaftFlat(app,doc,pls[0],start,side,"SHAFT_FLAT_"+(++k));
foreach(bool rt in new bool[]{false,true}){string s=rt?"RIGHT":"LEFT";
RMirror(app,doc,pls[0],.076,.072,.004,.080,rt,"ROT_OUTER_"+s,false);RMirror(app,doc,pls[0],.062,.0265,.004,.080,rt,"ROT_INNER_"+s,false);RMirror(app,doc,pls[0],.076,.0265,.002,.084,rt,"ROT_CAP_"+s,true);
RMirror(app,doc,pls[0],.036,.0252,.010,.067,rt,"STAT_COLLAR_"+s,false);RMirror(app,doc,pls[0],.070,.0252,.002,.077,rt,"STAT_PLATE_"+s,true);RMirror(app,doc,pls[0],.070,.064,.004,.079,rt,"STATOR_"+s,true);StatorHole(app,doc,pls[2],Z(.072,rt),"HOLE_STATOR_"+s);
object sm,tr;Begin(doc,pls[2],out sm,out tr);var seg=new List<object>();Circle(app,sm,tr,seg,0,.124,Z(.072,rt),.002);Finish(app,doc,sm,tr,seg,0,.006,.0125,"M4_SET_ENV_"+s);
RMirror(app,doc,pls[0],.076,.052,.021,.086,rt,"CARRIER_"+s,false);RMirror(app,doc,pls[0],.052,.025,.015,.092,rt,"BEARING_ENV_"+s,false);
Keeper(app,doc,pls[0],rt?.6605:.0375,.002,false,false,"KEEP_WALL_"+s);Keeper(app,doc,pls[0],rt?.654:.0395,.0065,true,true,"KEEPER_"+s);NewFork(app,doc,pls[0],Z(.050,rt),"FORK_"+s);
foreach(double x in new double[]{-.022,.022}){string t=s+(x<0?"_MINUS":"_PLUS");Ring(app,doc,pls[0],x,.135,.006,0,.030,rt?.6341:.0359,"BOLT_ROD_"+t);Hex(app,doc,pls[0],x,.135,.010,0,.004,rt?.6641:.0319,"M6_BOLT_"+t,true);Hex(app,doc,pls[0],x,.135,.010,.006,.005,rt?.6394:.0556,"M6_NUT_"+t);Ring(app,doc,pls[0],x,.135,.012,.0065,.0016,rt?.6625:.0359,"M6_WASH_"+t+"_OUT");Ring(app,doc,pls[0],x,.135,.012,.0065,.0016,rt?.6444:.054,"M6_WASH_"+t+"_IN");}}
Ring(app,doc,pls[0],0,.124,.076,.070,.486,.107,"SHELL");foreach(double z in new double[]{.05,.65})Tube(app,doc,pls[2],0,0,.05,z,.05,.1,.003,.006,.400,-.200,"REF_RAIL_"+(z<.1?"LEFT":"RIGHT"));
object[]bs=(object[])C(doc,"IPartDoc","GetBodies2",0,false);R(bs.Length==34,"Body count "+bs.Length);foreach(object b in bs)Rotate(app,doc,b,1.5*Math.PI/180);R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Rebuild");return doc;}
[STAThread]static int Main(string[]args){object app=null,doc=null,previous=null;string prevTitle=null;var report=new Dictionary<string,object>();using(var mx=new Mutex(false,@"Global\SolidWorksCodex_COM_Mutex")){bool held=false,owned=false;try{held=mx.WaitOne(10000);R(held,"COM busy");api=Assembly.LoadFrom(@"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.sldworks.dll");enums=Assembly.LoadFrom(@"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.swconst.dll");Guid id;CLSIDFromProgID("SldWorks.Application",out id);int expectedPID=Int32.Parse(args[3]);R(expectedPID!=10044,"Cannot use original user instance");app=AppAtPID(args[3]);int newpid=Convert.ToInt32(C(app,"ISldWorks","GetProcessID"));R(newpid==expectedPID,"Unexpected PID");owned=true;report["isolated_instance"]=true;report["own_process_id"]=newpid;S(app,"ISldWorks","Visible",false);previous=null;if(previous!=null){prevTitle=Convert.ToString(C(previous,"IModelDoc2","GetTitle"));report["previous_before"]=State(previous);}string output=Path.GetFullPath(args[0]);R(output.StartsWith(@"C:\Users\adm\Documents\Codex\2026-10-04\new-chat-2\outputs\")&&!File.Exists(output),"New own path required");doc=Build(app);report["bodies_before_save"]=Data(doc);report["intersections_before_save"]=Interferences(doc);
object ext=G(doc,"IModelDoc2","Extension"),prop=G(ext,"IModelDocExtension","CustomPropertyManager","");int type=E("swCustomInfoType_e","swCustomInfoText"),rep=E("swCustomPropertyAddOption_e","swCustomPropertyReplaceValue");C(prop,"ICustomPropertyManager","Add3","STATUS",type,"PRELIMINARY GEOMETRY - NOT FOR MANUFACTURING",rep);C(prop,"ICustomPropertyManager","Add3","REVISION",type,"R11_FLAT",rep);C(prop,"ICustomPropertyManager","Add3","SCOPE",type,"One flat roller OD76 face540 shaft25x620 with20mm flats24 each end. Blind keeper caps60x45x8.5, M6x30 bolts, simple labyrinth at1mm nominal gaps with M4 proxy fixation. Bearing25x52x15 centres501 apart. Two reference rails400. No actual threads fits bearing ring axial retention or wash qualification. Not integrated with whole conveyor. Geometry only not strength approval.",rep);
C(doc,"IModelDoc2","ShowNamedView2","*Isometric",7);C(doc,"IModelDoc2","ViewZoomtofit2");object[] sa={output,0,1,null,null,0,0};R(Convert.ToBoolean(C(ext,"IModelDocExtension","SaveAs3",sa))&&Convert.ToInt32(sa[5])==0,"Save");report["save_errors"]=sa[5];report["save_warnings"]=sa[6];C(app,"ISldWorks","CloseDoc",C(doc,"IModelDoc2","GetTitle"));object[] oa={output,1,1,"",0,0};doc=C(app,"ISldWorks","OpenDoc6",oa);R(doc!=null&&Convert.ToInt32(oa[4])==0,"Reopen");R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Reopen rebuild");report["reopened_bodies"]=Data(doc);report["reopened_intersections"]=Interferences(doc);report["service_intersections"]=ServiceInterferences(doc,app);
object[] ac={Convert.ToString(C(doc,"IModelDoc2","GetTitle")),true,0};C(app,"ISldWorks","ActivateDoc2",ac);C(doc,"IModelDoc2","ShowNamedView2","*Isometric",7);C(doc,"IModelDoc2","ViewZoomtofit2");object view=G(doc,"IModelDoc2","ActiveView");S(view,"IModelView","Scale2",Convert.ToDouble(G(view,"IModelView","Scale2"))*.75);C(doc,"IModelDoc2","GraphicsRedraw2");R(Convert.ToBoolean(C(doc,"IModelDoc2","SaveBMP",Path.GetFullPath(args[2]),1200,1000)),"Preview");object[] sf={1,0,0};R(Convert.ToBoolean(C(doc,"IModelDoc2","Save3",sf))&&Convert.ToInt32(sf[1])==0,"Final save");report["path"]=output;report["angle_deg"]=1.5;report["ok"]=true;
}catch(Exception e){report["ok"]=false;report["error"]=e.ToString();if(doc!=null)try{C(app,"ISldWorks","CloseDoc",C(doc,"IModelDoc2","GetTitle"));}catch{}}finally{if(previous!=null&&prevTitle!=null)try{report["previous_after"]=State(previous);object[] ac={prevTitle,true,0};C(app,"ISldWorks","ActivateDoc2",ac);}catch{}if(owned)try{C(app,"ISldWorks","ExitApp");}catch{}if(held)mx.ReleaseMutex();}}
File.WriteAllText(args[1],new JavaScriptSerializer{MaxJsonLength=10000000}.Serialize(report),new System.Text.UTF8Encoding(false));Console.WriteLine(new JavaScriptSerializer().Serialize(new{ok=report["ok"],error=report.ContainsKey("error")?report["error"]:null}));return (bool)report["ok"]?0:1;}}
