import fs from 'node:fs/promises';import path from 'node:path';import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const base='C:/Users/adm/Documents/Codex/2026-10-04/new-chat-2';const dat=JSON.parse(await fs.readFile(path.join(base,'work/structure_r03.json'),'utf8'));const wb=Workbook.create();
const calc=wb.worksheets.add('Балки');const profiles=wb.worksheets.add('Профили');const inp=wb.worksheets.add('Параметры');
function style(sh,range,widths){sh.showGridLines=false;sh.getRange(range).format.font={name:'Arial',size:11,color:'#202A33'};sh.getRange(range).format.rowHeight=30;sh.getRange(range).format.verticalAlignment='center';widths.forEach((w,i)=>sh.getRange(`${String.fromCharCode(65+i)}:${String.fromCharCode(65+i)}`).format.columnWidth=w);sh.getRange('A2').format.font={name:'Arial',size:15,bold:true};}
function head(sh,range){sh.getRange(range).format.fill='#263C52';sh.getRange(range).format.font={name:'Arial',size:11,bold:true,color:'#FFFFFF'};sh.getRange(range).format.rowHeight=38;sh.getRange(range).format.wrapText=true;}
style(inp,'A1:E19',[41,23,14,27,76]);inp.getRange('A2').values=[['Параметры проверки балок R03']];inp.getRange('A5:E5').values=[['Параметр','Значение','Единица','Статус','Основание']];head(inp,'A5:E5');
inp.getRange('A6:E15').values=[
 ['Модуль упругости E',200000,'МПа','Проектное допущение','Для сравнения принят E=200000; свойства конкретного Ст3 не подтверждены'],
 ['Плотность стали',7850,'кг/м³','Справочно','ArcelorMittal, таблица физических свойств, стр. 3; не сертификат выбранного Ст3'],
 ['Ускорение g',9.80665,'м/с²','Константа','Согласуется с расчётами R02'],
 ['Погонная масса материала',30,'кг/м','Исходный ориентир','Первоначальное задание; проверить фактическое распределение'],
 ['Пиковая масса в одной зоне',15,'кг','Подтверждено','Последнее уточнение пользователя; не масса падающего сброса'],
 ['Предлагаемый предел прогиба',2,'мм','Не согласовано','Критерий для выбора концепции; полный прогиб системы не рассчитан'],
 ['Дополнительная масса прочих узлов',null,'кг/м балки','Не задано','При пустом значении показан частичный расчёт: масса прочих узлов исключена'],
 ['Допускаемое напряжение',null,'МПа','Не задано','Сертификат, расчётная методика и коэффициенты ещё не назначены'],
 ['Длина одного модуля',5,'м','Проектный вариант','Два модуля примерно по 5 м разрешены; окончательные стыки не назначены'],
 ['Расстояние между осями балок',600,'мм','Проектный вариант','Предварительный резерв ширины для ленты 500 мм; ролики и крепления ещё не выбраны']];
inp.getRange('A6:E15').format.wrapText=true;inp.getRange('A6:E15').format.rowHeight=58;inp.getRange('B6:B15').format.fill='#FFF0C2';inp.getRange('A17:E17').merge();inp.getRange('A17').values=[['Источник физических свойств: https://tubulareurope.arcelormittal.com/sites/default/files/2023-12/structural_hollow_section_arcelormittal.pdf']];inp.getRange('A17:E17').format.wrapText=true;inp.getRange('A17:E17').format.rowHeight=45;
inp.getRange('A18:E18').merge();inp.getRange('A18').values=[['Документ 2020 года, срок экологической декларации до 2025. Использована таблица физических свойств, а не подтверждение её текущей действительности.']];inp.getRange('A18:E18').format.wrapText=true;inp.getRange('A18:E18').format.rowHeight=38;
style(profiles,'A1:F25',[43,24,24,24,13,61]);profiles.getRange('A2').values=[['Геометрия скруглённых труб: расчётные кандидаты']];profiles.getRange('A5:F5').values=[['Показатель','Кандидат A','Кандидат B','Кандидат C','Единица','Смысл']];head(profiles,'A5:F5');
const labels=[['Обозначение','—','Вычисляется из номинальных размеров'],['Высота h','мм','Высота при вертикальном изгибе'],['Ширина b','мм','Номинальное значение'],['Толщина t','мм','Не учитывает фактическую толщину и коррозию'],['Наружный радиус / толщина','—','Допущение геометрии; не нормативный допуск'],['Наружный радиус r','мм','r = коэффициент × t'],['Внутренний радиус','мм','r − t'],['Площадь наружного контура','мм²','b·h − (4−π)r²'],['Площадь пустоты','мм²','Скруглённый внутренний контур'],['Площадь металла A','мм²','Разность площадей'],['I наружного контура','мм⁴','Интеграл y² dA со скруглениями'],['I внутренней пустоты','мм⁴','Вычитаемая часть'],['I вертикального изгиба','мм⁴','Разность моментов инерции'],['Момент сопротивления W','мм³','2I/h'],['Погонная масса балки','кг/м','A × плотность × 10⁻⁶'],['Масса двух балок модуля','кг','Без поперечин, стоек и остального оборудования']];
for(let i=0;i<labels.length;i++){profiles.getRange(`A${6+i}`).values=[[labels[i][0]]];profiles.getRange(`E${6+i}:F${6+i}`).values=[[labels[i][1],labels[i][2]]];}
const inertia=(w,h,r)=>`(${w}*${h}^3/12-4*((${h}/2-${r})^2*(1-PI()/4)*${r}^2+(${h}/2-${r})*${r}^3/3+${r}^4*(1/3-PI()/16)))`;
for(let i=0;i<3;i++){const c=String.fromCharCode(66+i),p=dat.profiles[i];profiles.getRange(`${c}7:${c}10`).values=[[p.h_mm],[p.b_mm],[p.t_mm],[2]];profiles.getRange(`${c}6`).formulas=[[`=${c}7&"×"&${c}8&"×"&${c}9`]];profiles.getRange(`${c}11:${c}21`).formulas=[
 [`=${c}9*${c}10`],[`=${c}11-${c}9`],[`=${c}8*${c}7-(4-PI())*${c}11^2`],[`=(${c}8-2*${c}9)*(${c}7-2*${c}9)-(4-PI())*${c}12^2`],[`=${c}13-${c}14`],
 [`=${inertia(`${c}8`,`${c}7`,`${c}11`)}`],[`=${inertia(`(${c}8-2*${c}9)`,`(${c}7-2*${c}9)`,`${c}12`)}`],[`=${c}16-${c}17`],[`=2*${c}18/${c}7`],[`=${c}15*'Параметры'!B7*10^-6`],[`=2*${c}20*'Параметры'!B14`]];}
profiles.getRange('B7:D10').format.fill='#FFF0C2';profiles.getRange('A6:F21').format.wrapText=true;profiles.getRange('A6:F21').format.rowHeight=40;profiles.getRange('B11:D21').setNumberFormat('0.000');profiles.getRange('A23:F23').merge();profiles.getRange('A23').values=[['Свойства рассчитаны по номинальной геометрии с радиусами; это не паспорт поставщика. Сечение CAD-прототипа фиксировано и соответствует только исходному кандидату B.']];profiles.getRange('A23:F23').format.wrapText=true;profiles.getRange('A23:F23').format.rowHeight=43;
style(calc,'A1:H33',[25,14,12,23,24,22,24,28]);calc.getRange('A2').values=[['Вертикальный изгиб балок с собственным весом R03']];calc.getRange('A2:H2').merge();calc.getRange('A3:H3').merge();calc.getRange('A3').values=[['Частичный расчёт. Σ=q+вес балки+15 кг в середине: условная комбинация. Совместность q и местных 15 кг не подтверждена; собственные массы остальных узлов пока исключены.']];calc.getRange('A3:H3').format.wrapText=true;calc.getRange('A3:H3').format.rowHeight=55;
calc.getRange('A5:H5').values=[['Труба h×b×t','Пролёт, м','Доля q, β','w, Н/м','M суммы, Н·м','σ суммы, МПа','δ суммы, мм','Остаток по δ, кг/м']];head(calc,'A5:H5');
let row=6;for(let i=0;i<3;i++){const c=String.fromCharCode(66+i);for(const L of [2,2.5,10/3,5])for(const beta of [.5,1]){
 calc.getRange(`A${row}`).formulas=[[`='Профили'!${c}6`]];calc.getRange(`B${row}:C${row}`).values=[[L,beta]];
 calc.getRange(`D${row}:H${row}`).formulas=[[
 `=(C${row}*'Параметры'!B9+'Профили'!${c}20+IF(ISBLANK('Параметры'!B12),0,'Параметры'!B12))*'Параметры'!B8`,
 `=D${row}*B${row}^2/8+'Параметры'!B10*'Параметры'!B8*B${row}/4`,
 `=E${row}*1000/'Профили'!${c}19`,
 `=IF(OR(ISBLANK('Параметры'!B6),'Параметры'!B6<=0),"нет E",(5*D${row}*B${row}^4/384+'Параметры'!B10*'Параметры'!B8*B${row}^3/48)*10^9/('Параметры'!B6*'Профили'!${c}18))`,
 `=IF(OR(ISBLANK('Параметры'!B11),NOT(ISNUMBER(G${row}))),"не задано",MAX(0,('Параметры'!B11-G${row})*'Параметры'!B6*'Профили'!${c}18/10^9*384/(5*B${row}^4)/'Параметры'!B8))`
 ]];row++;}}
calc.getRange('B6:H29').setNumberFormat('0.000');calc.getRange('A6:H29').format.rowHeight=34;calc.getRange('B6:C29').format.fill='#FFF0C2';calc.getRange('A31:H31').merge();calc.getRange('A31').values=[['Остаток по δ — только возможная дополнительная равномерная масса при предлагаемом пределе 2 мм. Это не допустимая грузоподъёмность и не проверка полной прочности.']];calc.getRange('A31:H31').format.wrapText=true;calc.getRange('A31:H31').format.rowHeight=45;
calc.getRange('A32:H32').merge();calc.getRange('A32').values=[['Шарнирное опирание. Не включены натяжение, горизонтальный изгиб, кручение, устойчивость, стыки, стойки и основание. Коэффициенты динамики и допускаемое напряжение не назначены.']];calc.getRange('A32:H32').format.wrapText=true;calc.getRange('A32:H32').format.rowHeight=45;calc.freezePanes.freezeRows(5);
wb.recalculate();const tol=1e-6;for(let i=0;i<24;i++){const vals=calc.getRange(`D${6+i}:H${6+i}`).values[0],e=dat.comparisons[i];const ex=[e.w_N_m,e.M_conditional_sum_Nm,e.sigma_conditional_sum_MPa,e.deflection_conditional_sum_mm,e.stiffness_budget_extra_kg_m];if(vals.some((v,j)=>Math.abs(v-ex[j])>tol))throw Error(`Python independent comparison failed row ${6+i}`);}
const original=calc.getRange('G17').values[0][0];inp.getRange('B6').values=[[100000]];wb.recalculate();if(Math.abs(calc.getRange('G17').values[0][0]-2*original)>tol)throw Error('E sensitivity failed');inp.getRange('B6').values=[[null]];wb.recalculate();if(calc.getRange('G17').values[0][0]!=='нет E'||calc.getRange('H17').values[0][0]!=='не задано')throw Error('Missing E propagation failed');inp.getRange('B6').values=[[200000]];
inp.getRange('B12').values=[[10]];wb.recalculate();if(calc.getRange('G17').values[0][0]<=original)throw Error('Added dead mass not propagated');inp.getRange('B12').values=[[null]];wb.recalculate();if(Math.abs(calc.getRange('G17').values[0][0]-original)>tol)throw Error('Restore failed');
const error=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!',options:{useRegex:true,maxResults:40},maxChars:1000});await fs.writeFile(path.join(base,'work/frame_xlsx_error_r03.txt'),error.ndjson);
await fs.writeFile(path.join(base,'work/frame_xlsx_qa_r03.json'),JSON.stringify({all24CasesMatchIndependentPython:true,EAndDeadMassRecalculation:true,missingEPropagation:true,restored:true,engine:'Artifact Tool; native Excel not tested'},null,2));
for(const [sheet,range,name]of [[calc,'A2:H17','comparison_1'],[calc,'A18:H32','comparison_2'],[profiles,'A2:F23','profiles'],[inp,'A2:E18','parameters']]){const blob=await wb.render({sheetName:sheet.name,range,scale:1.2,format:'png'});await fs.writeFile(path.join(base,`work/r03_${name}_qa.png`),new Uint8Array(await blob.arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(wb)).save(path.join(base,'outputs/Ленточный_транспортер/02_Расчеты/ЛТ500_Сравнение_балок_R03.xlsx'));console.log(JSON.stringify({cases:24,checks:'passed',candidateDeflection_mm:original}));
