import fs from 'node:fs/promises';import path from 'node:path';import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const b='C:/Users/adm/Documents/Codex/2026-10-04/new-chat-2',d=JSON.parse(await fs.readFile(path.join(b,'work/loading_r09.json'),'utf8')),wb=Workbook.create(),s=wb.worksheets.add('Провис'),r=wb.worksheets.add('Ролик');
function base(s,range,widths){s.showGridLines=false;s.getRange(range).format.font={name:'Arial',size:11,color:'#202A33'};s.getRange(range).format.rowHeight=32;s.getRange(range).format.verticalAlignment='center';widths.forEach((w,j)=>s.getRange(`${String.fromCharCode(65+j)}:${String.fromCharCode(65+j)}`).format.columnWidth=w);s.getRange('A2').format.font={name:'Arial',size:15,bold:true};}
function head(s,rg){s.getRange(rg).format.fill='#263C52';s.getRange(rg).format.font={name:'Arial',size:11,bold:true,color:'#FFFFFF'};s.getRange(rg).format.wrapText=true;s.getRange(rg).format.rowHeight=54;}
function note(s,rg,txt){s.getRange(rg).merge();s.getRange(rg.split(':')[0]).values=[[txt]];s.getRange(rg).format.wrapText=true;s.getRange(rg).format.rowHeight=54;}
base(s,'A1:F34',[40,22,24,24,22,23]);s.getRange('A2').values=[['Загрузка и провис R09']];s.getRange('A4:B6').values=[['Фактическое пятно, м',null],['T рабочей для расчёта, Н',null],['Основание результата',null]];
s.getRange('B4').formulas=[[`=IF(ISBLANK(B28),"неизвестно",B28)`]];s.getRange('B5').formulas=[[`=IF(ISBLANK(B28),D10,IF(B28<0,"пятно <0",B29*COS(B24*PI()/180)*((B21+B22)*MAX(B26,B27)/(8*B25)+B23*IF(B28=0,1/(4*B25),IF(B28<MAX(B26,B27),(2*MAX(B26,B27)-B28)/(8*B25*MAX(B26,B27)),MAX(B26,B27)/(8*B25*B28))))))`]];note(s,'B6:F6','Пятно неизвестно: используется точечный случай. При подтверждённом пятне результат условен и учитывает обычный участок после зоны подачи.');
s.getRange('A9:F9').values=[['Пятно, м (0 = точка)','T загрузки, Н','T обычного участка, Н','T рабочей max, Н','R ролика загрузки, Н','R обычного ролика, Н']];head(s,'A9:F9');
const p=n=>`$B$${n}`,th=`${p(24)}*PI()/180`;function T(a,pp){return `${p(29)}*COS(${th})*((${p(21)}+${p(22)})*${pp}/(8*${p(25)})+${p(23)}*IF(${a}=0,1/(4*${p(25)}),IF(${a}<${pp},(2*${pp}-${a})/(8*${p(25)}*${pp}),${pp}/(8*${p(25)}*${a}))))`;}
function R(a,pp){return `${p(29)}*COS(${th})*((${p(21)}+${p(22)})*${pp}+${p(23)}*IF(${a}=0,1,IF(${a}<2*${pp},1-${a}/(4*${pp}),${pp}/${a})))`;}
d.cases.forEach((x,n)=>{let row=n+10;s.getRange(`A${row}`).values=[[x.footprint_m]];s.getRange(`B${row}:F${row}`).formulas=[[`=${T(`A${row}`,p(26))}`,`=${T(`A${row}`,p(27))}`,`=MAX(B${row}:C${row})`,`=${R(`A${row}`,p(26))}`,`=${R(`A${row}`,p(27))}`]];});s.getRange('B10:F14').setNumberFormat('0.00');s.getRange('A10:A14').setNumberFormat('0.00');s.getRange('A10:A14').format.fill='#FFF0C2';
note(s,'A16:F16','Частые ролики под подачей не распределяют порцию сами по себе. Если 15 кг сохраняются компактными, глобальная потребность 6,893 кН остаётся как в R08.');
s.getRange('A20:D20').values=[['Исходный параметр','Значение','Единица','Статус']];head(s,'A20:D20');s.getRange('A21:D29').values=[['q материала',30,'кг/м','Ориентир задания'],['q ленты',5,'кг/м','Допущение'],['Единственная локальная масса',15,'кг','Сочетание с q условно'],['Уклон',1.5,'град','Пример1,5 из1–2°'],['Относительный провис',.01,'доля','Предлагаемый ориентир1%'],['Шаг зоны загрузки',.25,'м','Кандидат'],['Шаг обычного участка',.75,'м','Сценарий R08'],['Подтверждённая длина пятна',null,'м','Пусто: неизвестна;0: точка'],['g',9.80665,'м/с²','Константа']];s.getRange('B21:B29').format.fill='#FFF0C2';s.getRange('B25').setNumberFormat('0.0%');s.getRange('A21:D29').format.wrapText=true;s.getRange('A21:D29').format.rowHeight=38;note(s,'A31:F31','R — нормальная нагрузка от ленты и материала на один ролик. Собственный вес ролика и удар не входят. Распределённая порция принята равномерной по длине.');note(s,'A33:F33',d.sources[0].url);
base(r,'A1:J36',[18,16,20,23,22,22,23,23,23,25]);r.getRange('A2').values=[['Ролик: нагрузки и отдельные оценки изгиба R09']];note(r,'A4:J4','Ось стационарная. Подшипники расположены около опор. Расчёт оси ниже — крайняя схема: вся нагрузка в середине пролёта600мм; точная частичная схема с двумя нагрузками приведена в JSON/PDF.');r.getRange('A7:J7').values=[['Шаг, м','k местной массы','P ленты, Н','P на ось с весом, Н','I оболочки, мм⁴','σ оболочки, МПа','δ оболочки, мм','σ оси (центр), МПа','δ оси (центр), мм','Макс. R подш., Н']];head(r,'A7:J7');
const S=n=>`'Провис'!$B$${n}`,U=n=>`$B$${n}`,ct=`COS(${S(24)}*PI()/180)`;
for(let n=0;n<9;n++){let row=n+8,pi=[.25,.5,.75][Math.floor(n/3)],kp=n%3+1;r.getRange(`A${row}:B${row}`).values=[[pi,kp]];r.getRange(`C${row}:J${row}`).formulas=[[`=${S(29)}*${ct}*((${S(21)}+${S(22)})*A${row}+${S(23)}*B${row})`,`=C${row}+${S(29)}*(${U(30)}*${ct}+${U(31)})`,`=PI()*(${U(22)}^4-${U(23)}^4)/64`,`=(C${row}+${U(30)}*${S(29)}*${ct})*${U(25)}/4*${U(22)}/(2*E${row})`,`=IF(OR(ISBLANK(${U(29)}),${U(29)}<=0),"нет E",(C${row}+${U(30)}*${S(29)}*${ct})*${U(25)}^3/(48*${U(29)}*E${row}))`,`=D${row}*${U(28)}/4*${U(26)}/(2*(PI()*${U(26)}^4/64))`,`=IF(OR(ISBLANK(${U(29)}),${U(29)}<=0),"нет E",D${row}*${U(28)}^3/(48*${U(29)}*(PI()*${U(26)}^4/64)))`,`=(${S(29)}*${ct}*(${S(21)}+${S(22)})*A${row}+${U(30)}*${S(29)}*${ct})/2+${S(23)}*B${row}*${S(29)}*${ct}*(.5+${U(32)}/${U(25)})`]];}
r.getRange('A8:J16').setNumberFormat('0.000');r.getRange('A8:B16').format.fill='#FFF0C2';note(r,'A18:J18','k=1/2/3 применён только к местным15кг как чувствительность. Это не установленный коэффициент удара. Допускаемые напряжения, ресурс, контакты/фиксация и коррозия не подтверждены.');
r.getRange('A21:D21').values=[['Габарит / допущение','Значение','Единица','Статус']];head(r,'A21:D21');r.getRange('A22:D32').values=[['D оболочки',76,'мм','Кандидат'],['d оболочки',70,'мм','Толщина3мм'],['Рабочая длина',540,'мм','Для ленты500'],['Пролёт оболочки',525,'мм','По серединам подшипников'],['Диаметр оси',25,'мм','Без ступеней/ослаблений'],['Полная длина оси',620,'мм','Габарит'],['Пролёт оси',600,'мм','Опоры на рельсах'],['E',200000,'МПа','Допущение'],['Масса вращающегося узла',d.mass_estimates.rotating_supported_mass_estimate_kg,'кг','Включает целые2подшипника для нагрузки'],['Масса оси',d.mass_estimates.shaft_kg,'кг','По габариту25×620'],['Поперечное смещение15кг',250,'мм','Край ленты:±250']];r.getRange('A22:D32').format.wrapText=true;r.getRange('A22:D32').format.rowHeight=44;r.getRange('A22:A32').format.wrapText=true;r.getRange('B22:B32').format.fill='#FFF0C2';r.getRange('B30:B31').setNumberFormat('0.000');note(r,'A34:J34','Подшипник25×52×15мм — только габаритный кандидат SKF6205-2RSH. Его масса0,13кг взята из каталога; ресурс и пригодность к воде/отбросам ещё не проверены. CAD не меняется автоматически при редактировании книги.');note(r,'A36:J36',d.sources[1].url);
function near(x,y){if(typeof x!=='number'||Math.abs(x-y)>1e-5)throw Error(`${x} != ${y}`);}
s.getRange('B5').setNumberFormat('0.00');wb.recalculate();d.cases.forEach((x,n)=>[x.T_loading_N,x.T_regular_N,x.T_global_carry_N,x.roller_loading_normal_N,x.roller_regular_normal_N].forEach((v,j)=>near(s.getRange(`B${n+10}:F${n+10}`).values[0][j],v)));near(s.getRange('B5').values[0][0],d.cases[0].T_global_carry_N);
for(let n=0;n<9;n++){let x=d.shaft_and_shell_screening.find(x=>x.pitch_m==[.25,.5,.75][Math.floor(n/3)]&&x.local_peak_multiplier_assumed==n%3+1&&x.transverse_peak_position_mm==250);const vals=r.getRange(`F${n+8}:J${n+8}`).values[0];near(vals[0],x.shell_conservative_sigma_MPa);near(vals[1],x.shell_conservative_deflection_mm);near(vals[3],x.shaft_all_load_at_mid_bound_mm);near(vals[4],x.bearing_right_N);}
s.getRange('B28').values=[[.5]];wb.recalculate();near(s.getRange('B5').values[0][0],d.cases[2].T_global_carry_N);s.getRange('B28').values=[[0]];wb.recalculate();near(s.getRange('B5').values[0][0],d.cases[0].T_global_carry_N);s.getRange('B28').values=[[null]];
s.getRange('B23').values=[[0]];wb.recalculate();near(s.getRange('D10').values[0][0],9.80665*Math.cos(1.5*Math.PI/180)*35*.75/.08);s.getRange('B23').values=[[15]];r.getRange('B29').values=[[null]];wb.recalculate();if(r.getRange('I8').values[0][0]!=='нет E')throw Error('missing E');r.getRange('B29').values=[[100000]];wb.recalculate();near(r.getRange('I8').values[0][0],2*d.shaft_and_shell_screening[0].shaft_all_load_at_mid_bound_mm);r.getRange('B29').values=[[200000]];wb.recalculate();near(s.getRange('B5').values[0][0],d.cases[0].T_global_carry_N);
await fs.writeFile(path.join(b,'work/loading_xlsx_qa_r09.json'),JSON.stringify({five_sag_reaction_cases_match_Python:true,nine_shell_bearing_and_shaft_bound_cases_match_Python:true,unknown_zero_half_meter_footprint_checked:true,zero_peak_and_missing_half_E_checked:true,inputs_restored:true,engine:'Artifact Tool; Microsoft Excel not tested'},null,2));
const scan=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:40},maxChars:1000});await fs.writeFile(path.join(b,'work/loading_xlsx_scan_r09.txt'),scan.ndjson);
for(const [sh,rg,n]of [[s,'A2:F16','sag'],[s,'A20:F33','inputs'],[r,'A2:J18','roller'],[r,'A21:J36','roller_inputs']]){let blob=await wb.render({sheetName:sh.name,range:rg,scale:1.1,format:'png'});await fs.writeFile(path.join(b,`work/r09_${n}_qa.png`),new Uint8Array(await blob.arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(wb)).save(path.join(b,'outputs/Ленточный_транспортер/02_Расчеты/ЛТ500_Расчёт_опор_загрузки_R09.xlsx'));console.log('R09 workbook verified');
