from pathlib import Path
B=Path(__file__).resolve().parent
old=(B/'CreateLoadingPrototype.cs').read_text(encoding='utf8');pre=old.split('static object Build(')[0].replace('class LoadingPrototype','class FlatR11')
pre=pre.replace('double start,string name){\nS(sm,','double start,string name,bool merge=false){\nS(sm,')
pre=pre.replace('0d,0d,false,false,false,false,false,false,true,start==0','0d,0d,false,false,false,false,merge,false,true,start==0')
pre=pre.replace('double length,double start,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();Circle','double length,double start,string name,bool merge=false){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();Circle')
pre=pre.replace('seg,2,length,start,name);}\nstatic void Hex','seg,2,length,start,name,merge);}\nstatic void Hex')
pre=pre.replace('double af,double id,double length,double start,string name){','double af,double id,double length,double start,string name,bool merge=false){')
pre=pre.replace('seg,2,length,start,name);}\nstatic void Fastener','seg,2,length,start,name,merge);}\nstatic void Fastener')
extra=r'''
static void RectSeg(object app,object sm,object tr,List<object>segs,double x1,double y1,double x2,double y2){double[,]pp={{x1,y1},{x2,y1},{x2,y2},{x1,y2}};for(int j=0;j<4;j++){double[]p=Point(app,tr,pp[j,0],pp[j,1],0),q=Point(app,tr,pp[(j+1)%4,0],pp[(j+1)%4,1],0);Line(sm,segs,p[0],p[1],q[0],q[1]);}}
static void FlatCircle(object app,object sm,object tr,List<object>segs,double a,double r,double yc){double b=Math.Sqrt(r*r-a*a);double[,]pp={{a,yc+b},{a,yc-b},{-a,yc-b},{-a,yc+b}};double[]p=Point(app,tr,pp[0,0],pp[0,1],0),q=Point(app,tr,pp[1,0],pp[1,1],0);Line(sm,segs,p[0],p[1],q[0],q[1]);p=q;q=Point(app,tr,-a,yc-b,0);double[]m=Point(app,tr,0,yc-r,0);Arc(sm,segs,p[0],p[1],q[0],q[1],m[0],m[1]);p=q;q=Point(app,tr,-a,yc+b,0);Line(sm,segs,p[0],p[1],q[0],q[1]);p=q;q=Point(app,tr,a,yc+b,0);m=Point(app,tr,0,yc+r,0);Arc(sm,segs,p[0],p[1],q[0],q[1],m[0],m[1]);}
static void CutProfile(object app,object doc,object sm,object tr,List<object>seg,int axis,double start,double depth,string name){S(sm,"ISketchManager","AddToDB",false);C(doc,"IModelDoc2","ClearSelection2",true);foreach(object sg in seg)C(sg,"ISketchSegment","Select4",true,null);C(doc,"IModelDoc2","SketchAddConstraints","sgFIXED");C(doc,"IModelDoc2","ClearSelection2",true);object inv=C(tr,"IMathTransform","Inverse");double[]p0=Point(app,inv,0,0,0),pn=Point(app,inv,0,0,1);double normal=pn[axis]-p0[axis];C(sm,"ISketchManager","InsertSketch",true);object sf=C(doc,"IModelDoc2","FeatureByPositionReverse",0);S(sf,"IFeature","Name",name+"_PROFILE");C(sf,"IFeature","Select2",false,0);object cut=C(G(doc,"IModelDoc2","FeatureManager"),"IFeatureManager","FeatureCut3",true,false,normal>0,0,0,depth,0d,false,false,false,false,0d,0d,false,false,false,false,false,false,true,false,false,false,E("swStartConditions_e","swStartOffset"),Math.Abs(start),start*normal<0);R(cut!=null,"Cut failed "+name);S(cut,"IFeature","Name",name);object[]ff=(object[])C(cut,"IFeature","GetFaces");S(C(ff[0],"IFace2","GetBody"),"IBody2","Name",name.StartsWith("SHAFT")?"SHAFT":name.Contains("LEFT")?"STATOR_LEFT":"STATOR_RIGHT");}
static void ShaftFlat(object app,object doc,object plane,double start,double side,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();RectSeg(app,sm,tr,seg,side>0?.010:-.020,.110,side>0?.020:-.010,.138);CutProfile(app,doc,sm,tr,seg,2,start,.024,name);}
static void StatorHole(object app,object doc,object plane,double z,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();Circle(app,sm,tr,seg,0,.124,z,.00215);CutProfile(app,doc,sm,tr,seg,0,.0125,.006,name);}
static void Keeper(object app,object doc,object plane,double start,double depth,bool bore,bool merge,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();RectSeg(app,sm,tr,seg,-.030,.100,.030,.145);foreach(double x in new double[]{-.022,.022})Circle(app,sm,tr,seg,x,.135,0,.00325);if(bore)FlatCircle(app,sm,tr,seg,.01025,.0128,.12425);Finish(app,doc,sm,tr,seg,2,depth,start,name,merge);}
static void NewFork(object app,object doc,object plane,double z,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();double a=.01025,r=.01275,y=.12425,b=Math.Sqrt(r*r-a*a);double[,]pp={{-.030,.100},{.030,.100},{.030,.145},{a,.145},{a,y-b}};for(int j=0;j<4;j++){double[]p=Point(app,tr,pp[j,0],pp[j,1],0),q=Point(app,tr,pp[j+1,0],pp[j+1,1],0);Line(sm,seg,p[0],p[1],q[0],q[1]);}double[]p1=Point(app,tr,a,y-b,0),p2=Point(app,tr,-a,y-b,0),m=Point(app,tr,0,y-r,0);Arc(sm,seg,p1[0],p1[1],p2[0],p2[1],m[0],m[1]);double[,]rr={{-a,y-b},{-a,.145},{-.030,.145},{-.030,.100}};for(int j=0;j<3;j++){double[]p=Point(app,tr,rr[j,0],rr[j,1],0),q=Point(app,tr,rr[j+1,0],rr[j+1,1],0);Line(sm,seg,p[0],p[1],q[0],q[1]);}foreach(double x in new double[]{-.022,.022})Circle(app,sm,tr,seg,x,.135,0,.00325);Finish(app,doc,sm,tr,seg,2,.008,z-.004,name);}
static double Z(double z,bool right){return right?.7-z:z;}
static void RMirror(object app,object doc,object plane,double od,double id,double length,double start,bool right,string name,bool merge){Ring(app,doc,plane,0,.124,od,id,length,right?.7-start-length:start,name,merge);}
static List<object> ServiceInterferences(object doc,object app){var kept=new List<object>();foreach(object b in (Array)C(doc,"IPartDoc","GetBodies2",0,false)){string n=Convert.ToString(G(b,"IBody2","Name"));if(n.StartsWith("M6_"))continue;object copy=C(b,"IBody2","Copy");S(copy,"IBody2","Name",n);double dz=0,dy=0;if(n.StartsWith("KEEPER_"))dz=n.Contains("LEFT")?-.015:.015;else if(!n.StartsWith("REF_")&&!n.StartsWith("FORK_"))dy=.035;double a=1.5*Math.PI/180;object mu=C(app,"ISldWorks","GetMathUtility");object tr=C(mu,"IMathUtility","CreateTransform",new object[]{new double[]{1,0,0,0,1,0,0,0,1,dy*Math.Sin(a),dy*Math.Cos(a),dz,1,0,0,0}});R(Convert.ToBoolean(C(copy,"IBody2","ApplyTransform",tr)),"Service move");kept.Add(copy);}return PairCheck(kept.ToArray());}
static List<object> PairCheck(object[]bs){var rr=new List<object>();for(int i=0;i<bs.Length;i++)for(int j=i+1;j<bs.Length;j++){object a=C(bs[i],"IBody2","Copy"),b=C(bs[j],"IBody2","Copy");object[]ar={E("swBodyOperationType_e","SWBODYINTERSECT"),b,0};object raw=C(a,"IBody2","Operations2",ar);double v=0;if(raw is Array)foreach(object rb in (Array)raw)v+=((double[])C(rb,"IBody2","GetMassProperties",7850d))[3];int err=Convert.ToInt32(ar[2]);R(err==0||err==5||err==6||err==1067,"Service Boolean error");R(v<1e-10,"Service interference "+G(bs[i],"IBody2","Name")+" / "+G(bs[j],"IBody2","Name"));rr.Add(new Dictionary<string,object>{{"a",G(bs[i],"IBody2","Name")},{"b",G(bs[j],"IBody2","Name")},{"volume_m3",v}});}return rr;}
'''
build=r'''static object Build(object app){object doc=C(app,"ISldWorks","NewDocument",@"C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2026\templates\gost-part.prtdot",0,0d,0d);R(doc!=null,"New part");var pls=new List<object>();object f=C(doc,"IModelDoc2","FirstFeature");while(f!=null){if(Convert.ToString(C(f,"IFeature","GetTypeName2"))=="RefPlane")pls.Add(f);f=C(f,"IFeature","GetNextFeature");}
Ring(app,doc,pls[0],0,.124,.025,0,.620,.040,"SHAFT");int k=0;foreach(double start in new double[]{.040,.636})foreach(double side in new double[]{-1,1})ShaftFlat(app,doc,pls[0],start,side,"SHAFT_FLAT_"+(++k));
foreach(bool rt in new bool[]{false,true}){string s=rt?"RIGHT":"LEFT";
RMirror(app,doc,pls[0],.076,.072,.004,.080,rt,"ROT_OUTER_"+s,false);RMirror(app,doc,pls[0],.062,.0265,.004,.080,rt,"ROT_INNER_"+s,false);RMirror(app,doc,pls[0],.076,.0265,.002,.084,rt,"ROT_CAP_"+s,true);
RMirror(app,doc,pls[0],.036,.0252,.010,.067,rt,"STAT_COLLAR_"+s,false);RMirror(app,doc,pls[0],.070,.0252,.002,.077,rt,"STAT_PLATE_"+s,true);RMirror(app,doc,pls[0],.070,.064,.004,.079,rt,"STATOR_"+s,true);StatorHole(app,doc,pls[2],Z(.072,rt),"HOLE_STATOR_"+s);
object sm,tr;Begin(doc,pls[2],out sm,out tr);var seg=new List<object>();Circle(app,sm,tr,seg,0,.124,Z(.072,rt),.002);Finish(app,doc,sm,tr,seg,0,.006,.0125,"M4_SET_ENV_"+s);
RMirror(app,doc,pls[0],.076,.052,.021,.086,rt,"CARRIER_"+s,false);RMirror(app,doc,pls[0],.052,.025,.015,.092,rt,"BEARING_ENV_"+s,false);
Keeper(app,doc,pls[0],rt?.6605:.0375,.002,false,false,"KEEP_WALL_"+s);Keeper(app,doc,pls[0],rt?.654:.0395,.0065,true,true,"KEEPER_"+s);NewFork(app,doc,pls[0],Z(.050,rt),"FORK_"+s);
foreach(double x in new double[]{-.022,.022}){string t=s+(x<0?"_MINUS":"_PLUS");Ring(app,doc,pls[0],x,.135,.006,0,.030,rt?.6341:.0359,"BOLT_ROD_"+t);Hex(app,doc,pls[0],x,.135,.010,0,.004,rt?.6641:.0319,"M6_BOLT_"+t,true);Hex(app,doc,pls[0],x,.135,.010,.006,.005,rt?.6394:.0556,"M6_NUT_"+t);Ring(app,doc,pls[0],x,.135,.012,.0065,.0016,rt?.6625:.0359,"M6_WASH_"+t+"_OUT");Ring(app,doc,pls[0],x,.135,.012,.0065,.0016,rt?.6444:.054,"M6_WASH_"+t+"_IN");}}
Ring(app,doc,pls[0],0,.124,.076,.070,.486,.107,"SHELL");foreach(double z in new double[]{.05,.65})Tube(app,doc,pls[2],0,0,.05,z,.05,.1,.003,.006,.400,-.200,"REF_RAIL_"+(z<.1?"LEFT":"RIGHT"));
object[]bs=(object[])C(doc,"IPartDoc","GetBodies2",0,false);R(bs.Length==34,"Body count "+bs.Length);foreach(object b in bs)Rotate(app,doc,b,1.5*Math.PI/180);R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Rebuild");return doc;}
'''
tail='[STAThread]'+old.split('[STAThread]')[1];tail=tail.replace('"R09"','"R11_FLAT"')
tail=tail.replace('Four loading rollers at250mm pitch. OD76 face540 shaft25x620. Bearing envelopes25x52x15 only. Open forks lack retainers, seal covers, fits, welds, adjustment. Two reference rail stubs1100. Not integrated with R07. Belt thickness8 and seating-to-belt170 assumed. Geometry only, not strength or safety approval.','One flat roller OD76 face540 shaft25x620 with20mm flats24 each end. Blind keeper caps60x45x8.5, M6x30 bolts, simple labyrinth at1mm nominal gaps with M4 proxy fixation. Bearing25x52x15 centres501 apart. Two reference rails400. No actual threads fits bearing ring axial retention or wash qualification. Not integrated with whole conveyor. Geometry only not strength approval.')
tail=tail.replace('report["reopened_intersections"]=Interferences(doc);','report["reopened_intersections"]=Interferences(doc);report["service_intersections"]=ServiceInterferences(doc,app);')
tail=tail.replace('C(doc,"IModelDoc2","ViewZoomtofit2");R(Convert.ToBoolean(C(doc,"IModelDoc2","SaveBMP"','C(doc,"IModelDoc2","ViewZoomtofit2");object view=G(doc,"IModelDoc2","ActiveView");S(view,"IModelView","Scale2",Convert.ToDouble(G(view,"IModelView","Scale2"))*.75);C(doc,"IModelDoc2","GraphicsRedraw2");R(Convert.ToBoolean(C(doc,"IModelDoc2","SaveBMP"')
(B/'CreateFlatRollerR11.cs').write_text(pre+extra+build+tail,encoding='utf8');print('R11 native source generated')
