from pathlib import Path
b=Path(__file__).parent;s=(b/'CreateSupportPrototype.cs').read_text(encoding='utf8');s=s[:s.index('static double Volume')].replace('class SupportPrototype','class SeatPrototype')
s+=r'''
static double[] Point(object app,object tr,double x,double y,double z){object mu=C(app,"ISldWorks","GetMathUtility");object p=C(mu,"IMathUtility","CreatePoint",new object[]{new double[]{x,y,z}});return (double[])G(C(p,"IMathPoint","MultiplyTransform",tr),"IMathPoint","ArrayData");}
static object Finish(object app,object doc,object sm,object tr,List<object> segs,int axis,double depth,double start,string name){
S(sm,"ISketchManager","AddToDB",false);C(doc,"IModelDoc2","ClearSelection2",true);bool add=false;foreach(object sg in segs){R(Convert.ToBoolean(C(sg,"ISketchSegment","Select4",add,null)),"Fix selection failed");add=true;}C(doc,"IModelDoc2","SketchAddConstraints","sgFIXED");C(doc,"IModelDoc2","ClearSelection2",true);
object inv=C(tr,"IMathTransform","Inverse");double[] p0=Point(app,inv,0,0,0),pn=Point(app,inv,0,0,1);double normal=pn[axis]-p0[axis];R(Math.Abs(Math.Abs(normal)-1)<1e-8,"Unexpected normal");C(sm,"ISketchManager","InsertSketch",true);object sf=C(doc,"IModelDoc2","FeatureByPositionReverse",0);S(sf,"IFeature","Name",name+"_PROFILE");C(sf,"IFeature","Select2",false,0);object fm=G(doc,"IModelDoc2","FeatureManager");object boss=C(fm,"IFeatureManager","FeatureExtrusion3",true,false,normal<0,0,0,depth,0d,false,false,false,false,0d,0d,false,false,false,false,false,false,true,start==0?0:E("swStartConditions_e","swStartOffset"),Math.Abs(start),start*normal<0);R(boss!=null,"Extrusion failed "+name);S(boss,"IFeature","Name",name);object[] faces=(object[])C(boss,"IFeature","GetFaces");R(faces.Length>0,"No faces");object body=C(faces[0],"IFace2","GetBody");S(body,"IBody2","Name",name);return body;
}
static object Tube(object app,object doc,object plane,int axis,double cx,double cy,double cz,double w,double h,double t,double r,double depth,double start,string name){
C(doc,"IModelDoc2","ClearSelection2",true);R(Convert.ToBoolean(C(plane,"IFeature","Select2",false,0)),"Plane select");object sm=G(doc,"IModelDoc2","SketchManager");C(sm,"ISketchManager","InsertSketch",true);object sk=G(sm,"ISketchManager","ActiveSketch"),tr=G(sk,"ISketch","ModelToSketchTransform");double[] q=Point(app,tr,cx,cy,cz);var segs=new List<object>();S(sm,"ISketchManager","AddToDB",true);
if(t>0){RR(sm,segs,q[0],q[1],w,h,r);RR(sm,segs,q[0],q[1],w-2*t,h-2*t,r-t);}else{Line(sm,segs,q[0]-w/2,q[1]-h/2,q[0]+w/2,q[1]-h/2);Line(sm,segs,q[0]+w/2,q[1]-h/2,q[0]+w/2,q[1]+h/2);Line(sm,segs,q[0]+w/2,q[1]+h/2,q[0]-w/2,q[1]+h/2);Line(sm,segs,q[0]-w/2,q[1]+h/2,q[0]-w/2,q[1]-h/2);}
return Finish(app,doc,sm,tr,segs,axis,depth,start,name);
}
static void Wedge(object app,object doc,object plane,double z,double a,double tc,string name){
C(doc,"IModelDoc2","ClearSelection2",true);C(plane,"IFeature","Select2",false,0);object sm=G(doc,"IModelDoc2","SketchManager");C(sm,"ISketchManager","InsertSketch",true);object tr=G(G(sm,"ISketchManager","ActiveSketch"),"ISketch","ModelToSketchTransform");var segs=new List<object>();S(sm,"ISketchManager","AddToDB",true);
double[,] pts={{-.05,.04-tc},{.05,.04-tc},{.05,.04-.05*Math.Tan(a)},{-.05,.04+.05*Math.Tan(a)}};for(int i=0;i<4;i++){int j=(i+1)%4;double[] p=Point(app,tr,pts[i,0],pts[i,1],0),q=Point(app,tr,pts[j,0],pts[j,1],0);Line(sm,segs,p[0],p[1],q[0],q[1]);}Finish(app,doc,sm,tr,segs,2,.06,z-.03,name);
}
static List<object> Data(object doc){var data=new List<object>();foreach(object body in (Array)C(doc,"IPartDoc","GetBodies2",0,false)){double[] mp=(double[])C(body,"IBody2","GetMassProperties",7850d);var planes=new List<object>();foreach(object f in (Array)C(body,"IBody2","GetFaces")){object surf=C(f,"IFace2","GetSurface");if(Convert.ToBoolean(C(surf,"ISurface","IsPlane")))planes.Add(new Dictionary<string,object>{{"plane",G(surf,"ISurface","PlaneParams")},{"area_m2",C(f,"IFace2","GetArea")}});}data.Add(new Dictionary<string,object>{{"name",G(body,"IBody2","Name")},{"volume_m3",mp[3]},{"centroid_m",new double[]{mp[0],mp[1],mp[2]}},{"planes",planes}});}return data;}
static double Volume(object doc){double v=0;foreach(object b in (Array)C(doc,"IPartDoc","GetBodies2",0,false))v+=((double[])C(b,"IBody2","GetMassProperties",7850d))[3];return v;}
static List<object> Interferences(object doc){object[] bs=(object[])C(doc,"IPartDoc","GetBodies2",0,false);var data=new List<object>();for(int i=0;i<bs.Length;i++)for(int j=i+1;j<bs.Length;j++){object a=C(bs[i],"IBody2","Copy"),b=C(bs[j],"IBody2","Copy");object[] args={E("swBodyOperationType_e","SWBODYINTERSECT"),b,0};object raw=C(a,"IBody2","Operations2",args);double v=0;if(raw is Array)foreach(object rb in (Array)raw){double[] mp=(double[])C(rb,"IBody2","GetMassProperties",7850d);v+=mp[3];}int error=Convert.ToInt32(args[2]);R(error==0||error==5||error==6||error==1067,"Unresolved boolean error "+error);R(v<1e-10,"Interference detected");data.Add(new Dictionary<string,object>{{"a",G(bs[i],"IBody2","Name")},{"b",G(bs[j],"IBody2","Name")},{"volume_m3",v},{"api_code",error}});}return data;}
static object Build(object app,double deg){object doc=C(app,"ISldWorks","NewDocument",@"C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2026\templates\gost-part.prtdot",0,0d,0d);R(doc!=null,"New part failed");var pls=new List<object>();object f=C(doc,"IModelDoc2","FirstFeature");while(f!=null){if(Convert.ToString(C(f,"IFeature","GetTypeName2"))=="RefPlane")pls.Add(f);f=C(f,"IFeature","GetNextFeature");}R(pls.Count>=3,"No default planes");double a=deg*Math.PI/180,tc=.010+.050*Math.Tan(a);
Tube(app,doc,pls[0],2,0,-tc,0,.100,.080,.004,.008,.7,0,"CROSSBEAM");
foreach(double z in new double[]{.05,.65}){string side=z<.1?"LEFT":"RIGHT";Tube(app,doc,pls[1],1,0,0,z,.05,.05,.003,.006,.542-tc,-.582,"LEG_"+side);Tube(app,doc,pls[1],1,0,0,z,.120,.150,0,0,.008,-.590,"PLATE_"+side);Wedge(app,doc,pls[0],z,a,tc,"SEAT_"+side);
foreach(double start in new double[]{-.3,0}){string nm="REF_RAIL_"+side+(start<0?"_IN":"_OUT");object body=Tube(app,doc,pls[2],0,0,.09,z,.05,.1,.003,.006,.3,start,nm);C(doc,"IModelDoc2","ClearSelection2",true);object sel=G(doc,"IModelDoc2","SelectionManager");object sd=C(sel,"ISelectionMgr","CreateSelectData");S(sd,"ISelectData","Mark",1);R(Convert.ToBoolean(C(body,"IBody2","Select2",false,sd)),"Body rotation select");object mv=C(G(doc,"IModelDoc2","FeatureManager"),"IFeatureManager","InsertMoveCopyBody2",0d,0d,0d,0d,0d,.04,z,0d,0d,-a,false,0);R(mv!=null,"Body rotation failed");S(mv,"IFeature","Name",nm+"_SLOPE");}}
R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Rebuild failed");R(((Array)C(doc,"IPartDoc","GetBodies2",0,false)).Length==11,"Expected 11 bodies");double expected=1334.7964473723105*.7e-6+2*540.8230016469242*(.542-tc)*1e-6+2*120*150*8e-9+2*.100*.060*tc+4*840.8230016469242*.3e-6;R(Math.Abs(Volume(doc)-expected)<1e-9,"Total volume differs");return doc;}
[STAThread]static int Main(string[]args){object app=null,doc=null,previous=null;string prevTitle=null;var report=new Dictionary<string,object>();using(var mx=new Mutex(false,@"Global\SolidWorksCodex_COM_Mutex")){bool held=false;try{held=mx.WaitOne(10000);R(held,"COM busy");api=Assembly.LoadFrom(@"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.sldworks.dll");enums=Assembly.LoadFrom(@"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.swconst.dll");Guid id;CLSIDFromProgID("SldWorks.Application",out id);GetActiveObject(ref id,IntPtr.Zero,out app);previous=G(app,"ISldWorks","IActiveDoc2");if(previous!=null){prevTitle=Convert.ToString(C(previous,"IModelDoc2","GetTitle"));report["previous_before"]=State(previous);}string output=Path.GetFullPath(args[0]);R(output.StartsWith(@"C:\Users\adm\Documents\Codex\2026-10-04\new-chat-2\outputs\")&&!File.Exists(output),"Invalid new destination");var variants=new List<object>();
foreach(double deg in new double[]{1,2,1.5}){doc=Build(app,deg);var v=new Dictionary<string,object>{{"angle_deg",deg},{"volume_m3",Volume(doc)},{"bodies",Data(doc)},{"intersections",Interferences(doc)}};variants.Add(v);if(deg!=1.5){C(app,"ISldWorks","CloseDoc",C(doc,"IModelDoc2","GetTitle"));doc=null;}}
report["variants"]=variants;object ext=G(doc,"IModelDoc2","Extension"),prop=G(ext,"IModelDocExtension","CustomPropertyManager","");int type=E("swCustomInfoType_e","swCustomInfoText"),replace=E("swCustomPropertyAddOption_e","swCustomPropertyReplaceValue");C(prop,"ICustomPropertyManager","Add3","STATUS",type,"PRELIMINARY GEOMETRY - NOT FOR MANUFACTURING",replace);C(prop,"ICustomPropertyManager","Add3","REVISION",type,"R05",replace);C(prop,"ICustomPropertyManager","Add3","SCOPE",type,"7 support bodies plus 4 reference rail stubs; two 100x60 tapered seats, min10 mm, 1.5deg downhill. Mid seating plane remains y40 mm above foot bottom y-590. No fixings, welds, belt loads or manufacturing approval.",replace);C(prop,"ICustomPropertyManager","Add3","MATERIAL",type,"St3 per brief, subgrade unconfirmed; density 7850 only in verification, not assigned CAD material.",replace);
C(doc,"IModelDoc2","ShowNamedView2","*Isometric",7);C(doc,"IModelDoc2","ViewZoomtofit2");object[] sa={output,0,1,null,null,0,0};R(Convert.ToBoolean(C(ext,"IModelDocExtension","SaveAs3",sa))&&Convert.ToInt32(sa[5])==0,"Save failed");report["save_errors"]=sa[5];report["save_warnings"]=sa[6];C(app,"ISldWorks","CloseDoc",C(doc,"IModelDoc2","GetTitle"));object[] oa={output,1,1,"",0,0};doc=C(app,"ISldWorks","OpenDoc6",oa);R(doc!=null&&Convert.ToInt32(oa[4])==0,"Reopen failed");R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Reopen rebuild failed");report["reopened_bodies"]=Data(doc);report["reopened_intersections"]=Interferences(doc);report["reopened_volume_m3"]=Volume(doc);C(doc,"IModelDoc2","ShowNamedView2","*Isometric",7);C(doc,"IModelDoc2","ViewZoomtofit2");R(Convert.ToBoolean(C(doc,"IModelDoc2","SaveBMP",Path.GetFullPath(args[2]),1200,1000)),"Preview save failed");object[] sf={1,0,0};R(Convert.ToBoolean(C(doc,"IModelDoc2","Save3",sf))&&Convert.ToInt32(sf[1])==0,"Final save failed");report["path"]=output;report["material_assigned"]=false;report["fixed_geometry"]=true;report["ok"]=true;
}catch(Exception e){report["ok"]=false;report["error"]=e.ToString();if(doc!=null)try{C(app,"ISldWorks","CloseDoc",C(doc,"IModelDoc2","GetTitle"));}catch{}}finally{if(previous!=null&&prevTitle!=null)try{report["previous_after"]=State(previous);object[] ac={prevTitle,true,0};C(app,"ISldWorks","ActivateDoc2",ac);}catch{}if(held)mx.ReleaseMutex();}}string json=new JavaScriptSerializer{MaxJsonLength=10000000}.Serialize(report);File.WriteAllText(args[1],json,new System.Text.UTF8Encoding(false));Console.WriteLine(new JavaScriptSerializer().Serialize(new{ok=report["ok"],error=report.ContainsKey("error")?report["error"]:null}));return (bool)report["ok"]?0:1;}
}
'''
(b/'CreateSeatPrototype.cs').write_text(s,encoding='utf8')
