from pathlib import Path
B=Path(r'C:\Users\adm\Documents\Codex\2026-10-04\new-chat-2')
src=(B/'work/CreateJointPrototype.cs').read_text(encoding='utf8').split('static object Build(')[0].replace('class JointPrototype','class LoadingPrototype')
src+=r'''
static void Fork(object app,object doc,object plane,double x,double z,string name){object sm,tr;Begin(doc,plane,out sm,out tr);var seg=new List<object>();double[,] pts={{x-.030,.100},{x+.030,.100},{x+.030,.145},{x+.0125,.145},{x+.0125,.124}};
for(int j=0;j<4;j++){double[]p=Point(app,tr,pts[j,0],pts[j,1],0),q=Point(app,tr,pts[j+1,0],pts[j+1,1],0);Line(sm,seg,p[0],p[1],q[0],q[1]);}
double[]p1=Point(app,tr,x+.0125,.124,0),p2=Point(app,tr,x-.0125,.124,0),pm=Point(app,tr,x,.1115,0);Arc(sm,seg,p1[0],p1[1],p2[0],p2[1],pm[0],pm[1]);
double[,] rest={{x-.0125,.124},{x-.0125,.145},{x-.030,.145},{x-.030,.100}};for(int j=0;j<3;j++){double[]p=Point(app,tr,rest[j,0],rest[j,1],0),q=Point(app,tr,rest[j+1,0],rest[j+1,1],0);Line(sm,seg,p[0],p[1],q[0],q[1]);}Finish(app,doc,sm,tr,seg,2,.008,z-.004,name);}
static void Rotate(object app,object doc,object body,double a){string name=Convert.ToString(G(body,"IBody2","Name"));C(doc,"IModelDoc2","ClearSelection2",true);object sd=C(G(doc,"IModelDoc2","SelectionManager"),"ISelectionMgr","CreateSelectData");S(sd,"ISelectData","Mark",1);R(Convert.ToBoolean(C(body,"IBody2","Select2",false,sd)),"Body select");object mv=C(G(doc,"IModelDoc2","FeatureManager"),"IFeatureManager","InsertMoveCopyBody2",0d,0d,0d,0d,0d,0d,0d,0d,0d,-a,false,0);R(mv!=null,"Move failed");S(mv,"IFeature","Name",name+"_SLOPE");object def=C(mv,"IFeature","GetDefinition");R(Convert.ToBoolean(C(def,"IMoveCopyBodyFeatureData","AccessSelections",doc,null)),"Move access");S(def,"IMoveCopyBodyFeatureData","TransformType",E("swMoveCopyBodyFeatureTransformType_e","swTransformType_Rotation"));S(def,"IMoveCopyBodyFeatureData","TransformReferenceEntity",null);S(def,"IMoveCopyBodyFeatureData","RotationOriginX",0d);S(def,"IMoveCopyBodyFeatureData","RotationOriginY",0d);S(def,"IMoveCopyBodyFeatureData","RotationOriginZ",0d);S(def,"IMoveCopyBodyFeatureData","TransformX",0d);S(def,"IMoveCopyBodyFeatureData","TransformY",0d);S(def,"IMoveCopyBodyFeatureData","TransformZ",-a);R(Convert.ToBoolean(C(mv,"IFeature","ModifyDefinition",def,doc,null)),"Move update");}
static object Build(object app){object doc=C(app,"ISldWorks","NewDocument",@"C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2026\templates\gost-part.prtdot",0,0d,0d);R(doc!=null,"New part");var pls=new List<object>();object f=C(doc,"IModelDoc2","FirstFeature");while(f!=null){if(Convert.ToString(C(f,"IFeature","GetTypeName2"))=="RefPlane")pls.Add(f);f=C(f,"IFeature","GetNextFeature");}R(pls.Count>=3,"Planes");
foreach(double z in new double[]{.05,.65})Tube(app,doc,pls[2],0,0,.05,z,.05,.1,.003,.006,1.1,-.55,"REF_RAIL_"+(z<.1?"LEFT":"RIGHT"));
int n=0;foreach(double x in new double[]{-.375,-.125,.125,.375}){n++;Ring(app,doc,pls[0],x,.124,.076,.070,.510,.095,"SHELL_"+n);Ring(app,doc,pls[0],x,.124,.025,0,.620,.040,"SHAFT_"+n);
foreach(double start in new double[]{.080,.605}){string side=start<.1?"LEFT":"RIGHT";Ring(app,doc,pls[0],x,.124,.076,.052,.015,start,"CARRIER_"+n+"_"+side);Ring(app,doc,pls[0],x,.124,.052,.025,.015,start,"BEARING_ENV_"+n+"_"+side);}
foreach(double z in new double[]{.05,.65})Fork(app,doc,pls[0],x,z,"FORK_"+n+"_"+(z<.1?"LEFT":"RIGHT"));}
object[] bs=(object[])C(doc,"IPartDoc","GetBodies2",0,false);R(bs.Length==34,"Body count");foreach(object body in bs)Rotate(app,doc,body,1.5*Math.PI/180);R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Rebuild");return doc;}
[STAThread]static int Main(string[]args){object app=null,doc=null,previous=null;string prevTitle=null;var report=new Dictionary<string,object>();using(var mx=new Mutex(false,@"Global\SolidWorksCodex_COM_Mutex")){bool held=false;try{held=mx.WaitOne(10000);R(held,"COM busy");api=Assembly.LoadFrom(@"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.sldworks.dll");enums=Assembly.LoadFrom(@"C:\Program Files\SOLIDWORKS Corp\SOLIDWORKS\api\redist\SolidWorks.Interop.swconst.dll");Guid id;CLSIDFromProgID("SldWorks.Application",out id);GetActiveObject(ref id,IntPtr.Zero,out app);previous=G(app,"ISldWorks","IActiveDoc2");if(previous!=null){prevTitle=Convert.ToString(C(previous,"IModelDoc2","GetTitle"));report["previous_before"]=State(previous);}string output=Path.GetFullPath(args[0]);R(output.StartsWith(@"C:\Users\adm\Documents\Codex\2026-10-04\new-chat-2\outputs\")&&!File.Exists(output),"New own path required");doc=Build(app);report["bodies_before_save"]=Data(doc);report["intersections_before_save"]=Interferences(doc);
object ext=G(doc,"IModelDoc2","Extension"),prop=G(ext,"IModelDocExtension","CustomPropertyManager","");int type=E("swCustomInfoType_e","swCustomInfoText"),rep=E("swCustomPropertyAddOption_e","swCustomPropertyReplaceValue");C(prop,"ICustomPropertyManager","Add3","STATUS",type,"PRELIMINARY GEOMETRY - NOT FOR MANUFACTURING",rep);C(prop,"ICustomPropertyManager","Add3","REVISION",type,"R09",rep);C(prop,"ICustomPropertyManager","Add3","SCOPE",type,"Four loading rollers at250mm pitch. OD76 face540 shaft25x620. Bearing envelopes25x52x15 only. Open forks lack retainers, seal covers, fits, welds, adjustment. Two reference rail stubs1100. Not integrated with R07. Belt thickness8 and seating-to-belt170 assumed. Geometry only, not strength or safety approval.",rep);
C(doc,"IModelDoc2","ShowNamedView2","*Isometric",7);C(doc,"IModelDoc2","ViewZoomtofit2");object[] sa={output,0,1,null,null,0,0};R(Convert.ToBoolean(C(ext,"IModelDocExtension","SaveAs3",sa))&&Convert.ToInt32(sa[5])==0,"Save");report["save_errors"]=sa[5];report["save_warnings"]=sa[6];C(app,"ISldWorks","CloseDoc",C(doc,"IModelDoc2","GetTitle"));object[] oa={output,1,1,"",0,0};doc=C(app,"ISldWorks","OpenDoc6",oa);R(doc!=null&&Convert.ToInt32(oa[4])==0,"Reopen");R(Convert.ToBoolean(C(doc,"IModelDoc2","ForceRebuild3",false)),"Reopen rebuild");report["reopened_bodies"]=Data(doc);report["reopened_intersections"]=Interferences(doc);
object[] ac={Convert.ToString(C(doc,"IModelDoc2","GetTitle")),true,0};C(app,"ISldWorks","ActivateDoc2",ac);C(doc,"IModelDoc2","ShowNamedView2","*Isometric",7);C(doc,"IModelDoc2","ViewZoomtofit2");R(Convert.ToBoolean(C(doc,"IModelDoc2","SaveBMP",Path.GetFullPath(args[2]),1200,1000)),"Preview");object[] sf={1,0,0};R(Convert.ToBoolean(C(doc,"IModelDoc2","Save3",sf))&&Convert.ToInt32(sf[1])==0,"Final save");report["path"]=output;report["angle_deg"]=1.5;report["ok"]=true;
}catch(Exception e){report["ok"]=false;report["error"]=e.ToString();if(doc!=null)try{C(app,"ISldWorks","CloseDoc",C(doc,"IModelDoc2","GetTitle"));}catch{}}finally{if(previous!=null&&prevTitle!=null)try{report["previous_after"]=State(previous);object[] ac={prevTitle,true,0};C(app,"ISldWorks","ActivateDoc2",ac);}catch{}if(held)mx.ReleaseMutex();}}
File.WriteAllText(args[1],new JavaScriptSerializer{MaxJsonLength=10000000}.Serialize(report),new System.Text.UTF8Encoding(false));Console.WriteLine(new JavaScriptSerializer().Serialize(new{ok=report["ok"],error=report.ContainsKey("error")?report["error"]:null}));return (bool)report["ok"]?0:1;}}
'''
src=src.replace('R(doc!=null,"New part")','R(doc!=null,"New part; revision="+C(app,"ISldWorks","RevisionNumber")+"; command="+G(app,"ISldWorks","CommandInProgress"))')
src=src.replace('bool held=false;try{','bool held=false,owned=false;try{')
src=src.replace('GetActiveObject(ref id,IntPtr.Zero,out app);previous=G(app,"ISldWorks","IActiveDoc2");', 'object existing;GetActiveObject(ref id,IntPtr.Zero,out existing);int oldpid=Convert.ToInt32(C(existing,"ISldWorks","GetProcessID"));app=Activator.CreateInstance(Type.GetTypeFromProgID("SldWorks.Application"));int newpid=Convert.ToInt32(C(app,"ISldWorks","GetProcessID"));R(newpid!=oldpid,"Instance is not isolated");owned=true;report["isolated_instance"]=true;report["own_process_id"]=newpid;S(app,"ISldWorks","Visible",false);previous=null;')
src=src.replace('if(held)mx.ReleaseMutex();','if(owned)try{C(app,"ISldWorks","ExitApp");}catch{}if(held)mx.ReleaseMutex();')
src=src.replace('object existing;GetActiveObject(ref id,IntPtr.Zero,out existing);int oldpid=Convert.ToInt32(C(existing,"ISldWorks","GetProcessID"));app=Activator.CreateInstance(Type.GetTypeFromProgID("SldWorks.Application"));int newpid=Convert.ToInt32(C(app,"ISldWorks","GetProcessID"));R(newpid!=oldpid,"Instance is not isolated");', 'var oldpids=new HashSet<int>();foreach(var proc in System.Diagnostics.Process.GetProcessesByName("SLDWORKS"))oldpids.Add(proc.Id);app=Activator.CreateInstance(api.GetType("SolidWorks.Interop.sldworks.SldWorksClass"));int newpid=Convert.ToInt32(C(app,"ISldWorks","GetProcessID"));R(!oldpids.Contains(newpid),"Instance is not isolated");')
src=src.replace('using System;','using System;using System.Runtime.InteropServices.ComTypes;')
src=src.replace('static Assembly api,enums;',r'''[DllImport("ole32.dll")]static extern int GetRunningObjectTable(int reserved,out IRunningObjectTable rot);[DllImport("ole32.dll")]static extern int CreateBindCtx(int reserved,out IBindCtx ctx);
static object AppAtPID(string pid){for(int k=0;k<60;k++){IRunningObjectTable rot;GetRunningObjectTable(0,out rot);IEnumMoniker en;rot.EnumRunning(out en);IMoniker[]ms=new IMoniker[1];while(en.Next(1,ms,IntPtr.Zero)==0){IBindCtx ctx;CreateBindCtx(0,out ctx);string name;ms[0].GetDisplayName(ctx,null,out name);if(name=="SolidWorks_PID_"+pid){object raw;rot.GetObject(ms[0],out raw);return Marshal.CreateWrapperOfType(raw,api.GetType("SolidWorks.Interop.sldworks.SldWorksClass"));}}Thread.Sleep(500);}throw new Exception("Own PID did not register in ROT");}
static Assembly api,enums;''')
src=src.replace('var oldpids=new HashSet<int>();foreach(var proc in System.Diagnostics.Process.GetProcessesByName("SLDWORKS"))oldpids.Add(proc.Id);app=Activator.CreateInstance(api.GetType("SolidWorks.Interop.sldworks.SldWorksClass"));int newpid=Convert.ToInt32(C(app,"ISldWorks","GetProcessID"));R(!oldpids.Contains(newpid),"Instance is not isolated");','int expectedPID=Int32.Parse(args[3]);R(expectedPID!=10044,"Cannot use original user instance");app=AppAtPID(args[3]);int newpid=Convert.ToInt32(C(app,"ISldWorks","GetProcessID"));R(newpid==expectedPID,"Unexpected PID");')
(B/'work/CreateLoadingPrototype.cs').write_text(src,encoding='utf8')
print('C# source prepared')
