import fs from 'node:fs/promises';import path from 'node:path';import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const b='C:/Users/adm/Documents/Codex/2026-10-04/new-chat-2',d=JSON.parse(await fs.readFile(path.join(b,'work/reinforce_r06.json'),'utf8')),wb=Workbook.create(),v=wb.worksheets.add('Вариант'),c=wb.worksheets.add('Пластины'),i=wb.worksheets.add('Параметры');
function style(s,r,w){s.showGridLines=false;s.getRange(r).format.font={name:'Arial',size:11,color:'#202A33'};s.getRange(r).format.rowHeight=35;s.getRange(r).format.verticalAlignment='center';w.forEach((n,j)=>s.getRange(`${String.fromCharCode(65+j)}:${String.fromCharCode(65+j)}`).format.columnWidth=n);s.getRange('A2').format.font={name:'Arial',size:15,bold:true};}
function head(s,r){s.getRange(r).format.fill='#263C52';s.getRange(r).format.font={name:'Arial',size:11,bold:true,color:'#FFFFFF'};s.getRange(r).format.wrapText=true;s.getRange(r).format.rowHeight=48;}
function note(s,r,t){s.getRange(r).merge();s.getRange(r.split(':')[0]).values=[[t]];s.getRange(r).format.wrapText=true;s.getRange(r).format.rowHeight=56;}
style(i,'A1:D44',[46,25,15,88]);i.getRange('A2').values=[['Параметры усиления R06']];i.getRange('A5:D5').values=[['Параметр','Значение','Единица','Источник / статус']];head(i,'A5:D5');
i.getRange('A6:D42').values=[
['E',200000,'МПа','Допущение упругой модели'],['Плотность',7850,'кг/м³','Расчёт массы'],['g',9.80665,'м/с²','Константа'],['Огибающая опоры R04',d.load_from_R04_N,'Н','q + трубы + местные 15 кг, условная комбинация'],['Уклон седла',1.5,'град','Временное значение 1–2°'],['Пластина вдоль движения',120,'мм','Кандидат после расчёта'],['Пластина поперечная',80,'мм','Кандидат после расчёта'],['Толщина выбранной пластины',12,'мм','По предлагаемому δ≤0,05 мм при b=38, L=112'],['Толщина боковой щеки',6,'мм','Кандидат; эксцентриситет нагрузки t/2'],['Высота щеки',80,'мм','Соответствует высоте трубы'],['Поперечная длина щеки',80,'мм','Геометрия усиления'],['Наружная ширина трубы',100,'мм','R04'],['Стенка трубы',4,'мм','R04; прочность поставки не подтверждена'],['Радиус трубы',8,'мм','Номинальная геометрия R04'],['Ориентир прогиба пластины',.05,'мм','Предлагаемый частичный критерий, не норматив'],['Катет шва-кандидата',3,'мм','Идеальный равнокатетный 45° шов, нормативный минимум/WPS открыты'],['Рабочая длина одного шва',54,'мм','На прямой части 64 мм, отступ 5 мм с каждого края'],['Эксцентриситет одной щеки',null,'мм','Половина её толщины'],['Стойка R04 без седла',542,'мм','Условная средняя модель'],['Лента по середине',800,'мм','Точка отсчёта условна'],['Лента — опирание рельса',170,'мм','Допущение до роликов'],['Высота поперечины',80,'мм','R04'],['Толщина базовой плиты',8,'мм','Геометрическая заготовка'],['Длина базовой плиты',120,'мм','R04'],['Ширина базовой плиты',150,'мм','R04'],['Длина поперечины',700,'мм','R04'],['Площадь сечения поперечины',1334.7964473723105,'мм²','Геометрия R04; размеры труб здесь не меняются'],['Площадь стойки',540.8230016469242,'мм²','Геометрия R04'],['Площадь рельса',840.8230016469242,'мм²','Геометрия R03'],['Справочный рельс: длина',300,'мм','Четыре отрезка, не полные модули'],['Длина седла',100,'мм','R05'],['Ширина седла',60,'мм','R05'],['Минимум толщины седла',10,'мм','R05, повторно проверен'],['Эффективная ширина полосы',38,'мм','Плоская нижняя поверхность рельса'],['Пролёт по осям щёк',null,'мм','Ширина трубы + толщина щеки'],['Пролёт по наружным граням',null,'мм','Ширина трубы + 2 толщины щеки'],['Верхний угол диапазона',2,'град','Для скатывающей составляющей'] ];
i.getRange('B23').formulas=[['=B14/2']];i.getRange('B40').formulas=[['=B17+B14']];i.getRange('B41').formulas=[['=B17+2*B14']];i.getRange('A6:D42').format.wrapText=true;i.getRange('A6:D42').format.rowHeight=44;i.getRange('B6:B42').format.fill='#FFF0C2';for(const r of [23,40,41])i.getRange(`B${r}`).format.fill='#E9F2EE';note(i,'A44:D44','Геометрия шва a=k/√2 принята для идеального равнокатетного шва 45°. Источник терминов a/z: https://www.twi-global.com/technical-knowledge/job-knowledge/design-part-1-090. Нормативная проверка швов не выполнена.');
style(v,'A1:F39',[36,24,20,22,40,40]);v.getRange('A2:F2').merge();v.getRange('A2').values=[['Усиление опорной зоны R06 — выбранный кандидат']];note(v,'A3:F3','Пластина опирается на две наружные щеки. Жёсткость верхней стенки трубы не используется в этом пути нагрузки. Условная P целиком на одну площадку; швы одной щеки проверены номинально на всю P. Не для изготовления.');
const labels=[['Толщина седла по центру','мм','При текущем угле'],['Объём одной пластины','м³','Без отверстий'],['Объём одной щеки','м³','Геометрия заготовки'],['Объём одного седла','м³','Усреднённая толщина'],['P для выбранного усиления','Н','Огибающая + вес 2 седел/2 пластин/4 щёк'],['Средняя стойка','мм','Сохранение плоскости опирания рельса'],['Объём опоры','м³','13 тел, без швов и крепежа'],['Масса опоры','кг','Не масса транспортёра'],['Масса с 4 отрезками рельса','кг','Справочная геометрия'],['Пролёт по осям щёк','мм','Средние линии опор'],['Прогиб пластины по осям','мм','Сосредоточенная сила по центру'],['Прогиб при наружном пролёте','мм','Геометрическая чувствительность'],['σ пластины по осям','МПа','Допускаемое напряжение отсутствует'],['Прогиб седла при пролёте 100','мм','Частичная верхняя оценка'],['Горло идеального шва','мм','k / √2'],['Площадь 2 швов одной щеки','мм²','Две линии длиной по 54 мм'],['τ двух швов','МПа','Вся P на одну щеку'],['I группы швов','мм⁴','Для момента от эксцентриситета'],['σ номинальное швов','МПа','M=P·tщеки/2'],['Эквивалентное номинальное','МПа','√(σ²+3τ²), не нормативный допуск'],['Скатывающая составляющая','Н','Без неизвестной тяги ленты']];
labels.forEach((x,n)=>{let r=n+6;v.getRange(`A${r}:B${r}`).merge();v.getRange(`A${r}`).values=[[x[0]]];v.getRange(`D${r}`).values=[[x[1]]];v.getRange(`E${r}:F${r}`).merge();v.getRange(`E${r}`).values=[[x[2]]];});
const guard=(f)=>`=IF(OR(ISBLANK('Параметры'!B6),'Параметры'!B6<=0),"нет E",${f})`;
v.getRange('C6:C26').formulas=[ ["='Параметры'!B38+'Параметры'!B36/2*TAN('Параметры'!B10*PI()/180)"],["='Параметры'!B11*'Параметры'!B12*'Параметры'!B13*10^-9"],["='Параметры'!B14*'Параметры'!B15*'Параметры'!B16*10^-9"],["='Параметры'!B36*'Параметры'!B37*C6*10^-9"],["='Параметры'!B9+(2*C7+4*C8+2*C9)*'Параметры'!B7*'Параметры'!B8"],["='Параметры'!B24-C6-'Параметры'!B13"],["=('Параметры'!B32*'Параметры'!B31+2*'Параметры'!B33*C11+2*'Параметры'!B29*'Параметры'!B30*'Параметры'!B28)*10^-9+2*C7+4*C8+2*C9"],["=C12*'Параметры'!B7"],["=(C12+4*'Параметры'!B34*'Параметры'!B35*10^-9)*'Параметры'!B7"],["='Параметры'!B40"],[guard("C10*C15^3/(48*'Параметры'!B6*('Параметры'!B39*'Параметры'!B13^3/12))")],[guard("C10*'Параметры'!B41^3/(48*'Параметры'!B6*('Параметры'!B39*'Параметры'!B13^3/12))")],["=6*(C10*C15/4)/('Параметры'!B39*'Параметры'!B13^2)"],[guard("C10*'Параметры'!B36^3/(48*'Параметры'!B6*('Параметры'!B39*'Параметры'!B38^3/12))")],["='Параметры'!B21/SQRT(2)"],["=2*C20*'Параметры'!B22"],["=C10/C21"],["=2*C20*'Параметры'!B22^3/12"],["=C10*'Параметры'!B23*'Параметры'!B22/2/C23"],["=SQRT(C24^2+3*C22^2)"],["=C10*SIN('Параметры'!B42*PI()/180)"] ];
v.getRange('C6:C26').setNumberFormat('0.000');for(const r of [7,8,9,12])v.getRange(`C${r}`).setNumberFormat('0.000000000');v.getRange('A6:F26').format.wrapText=true;v.getRange('A6:F26').format.rowHeight=42;
v.getRange('A29:E29').values=[['Ось, мм','Лента, мм','Верх трубы, мм','Верх пластины, мм','Стойка, мм']];head(v,'A29:E29');
for(let n=0;n<5;n++){let r=n+30;v.getRange(`A${r}`).values=[[[200,2600,5000,7400,9800][n]]];v.getRange(`B${r}:E${r}`).formulas=[[`='Параметры'!B25+(5000-A${r})*TAN('Параметры'!B10*PI()/180)`,`=B${r}-'Параметры'!B26-$C$6-'Параметры'!B13`,`=C${r}+'Параметры'!B13`,`=C${r}-'Параметры'!B27-'Параметры'!B28`]];}
v.getRange('A30:E34').setNumberFormat('0.000');note(v,'A36:F36','Швы-кандидаты, материал/допуски, контакт, фиксация седла, продольные усилия ленты, связи и основание не утверждены. Модель CAD фиксирована и не изменяется вместе с Excel.');
style(c,'A1:H45',[16,18,21,23,22,24,22,26]);c.getRange('A2:H2').merge();c.getRange('A2').values=[['Сравнение 36 вариантов пластины усиления']];note(c,'A3:H3','P включает вес усиливающих деталей для соответствующей толщины пластины. Изгиб отдельной полосы с шарнирным опиранием на щеках, без вклада трубы. Прогиб ≤0,05 мм — предлагаемый ориентир, не проверка прочности.');c.getRange('A5:H5').values=[['t, мм','Пролёт, мм','Эффективная ширина, мм','P, Н','σ, МПа','δ, мм','δ ≤ ориентир','Масса 2 пластин, кг']];head(c,'A5:H5');
d.cap_cases.forEach((x,n)=>{let r=n+6;c.getRange(`A${r}:C${r}`).values=[[x.t_mm,x.span_mm,x.effective_width_mm]];c.getRange(`D${r}:H${r}`).formulas=[[
`='Параметры'!B9+(2*'Параметры'!B11*'Параметры'!B12*A${r}*10^-9+4*'Вариант'!C8+2*'Вариант'!C9)*'Параметры'!B7*'Параметры'!B8`,`=6*(D${r}*B${r}/4)/(C${r}*A${r}^2)`,guard(`D${r}*B${r}^3/(48*'Параметры'!B6*(C${r}*A${r}^3/12))`),`=IF(ISNUMBER(F${r}),IF(F${r}<='Параметры'!B20,"да","нет"),"не задано")`,`=2*'Параметры'!B11*'Параметры'!B12*A${r}*10^-9*'Параметры'!B7`]];});c.getRange('D6:F41').setNumberFormat('0.0000');c.getRange('H6:H41').setNumberFormat('0.000');c.getRange('A6:C41').format.fill='#FFF0C2';note(c,'A43:H43','Выбран t=12 мм: для ширины 38 мм и пролёта 112 мм δ≈0,039 мм. Средняя стойка короче R05 на толщину пластины. Точки опирания, нормы сварки и полная прочность не подтверждены.');
wb.recalculate();function near(a,e){if(typeof a!=='number'||Math.abs(a-e)>1e-6)throw Error(`${a} vs ${e}`);}
d.cap_cases.forEach((x,n)=>{const vals=c.getRange(`D${n+6}:F${n+6}`).values[0];[x.P_N,x.sigma_MPa,x.delta_mm].forEach((e,j)=>near(vals[j],e));});near(v.getRange('C13').values[0][0],d.variants[1].stand_mass_kg);near(v.getRange('C16').values[0][0],d.cap_selected.delta_mm);near(v.getRange('C25').values[0][0],d.weld_selected.equivalent_nominal_MPa);
for(const th of [1,2]){i.getRange('B10').values=[[th]];wb.recalculate();const exp=d.variants.find(x=>x.angle_deg===th);near(v.getRange('C13').values[0][0],exp.stand_mass_kg);near(v.getRange('E30').values[0][0],exp.stations[0].leg_length_mm);}i.getRange('B10').values=[[1.5]];i.getRange('B6').values=[[100000]];wb.recalculate();near(v.getRange('C16').values[0][0],2*d.cap_selected.delta_mm);i.getRange('B6').values=[[null]];wb.recalculate();if(v.getRange('C16').values[0][0]!=='нет E'||c.getRange('G6').values[0][0]!=='не задано')throw Error('Missing E');i.getRange('B6').values=[[200000]];i.getRange('B21').values=[[4]];wb.recalculate();if(v.getRange('C25').values[0][0]>=d.weld_selected.equivalent_nominal_MPa)throw Error('Weld sensitivity');i.getRange('B21').values=[[3]];wb.recalculate();near(v.getRange('C25').values[0][0],d.weld_selected.equivalent_nominal_MPa);
const scan=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:40},maxChars:1000});await fs.writeFile(path.join(b,'work/reinforce_xlsx_scan_r06.txt'),scan.ndjson);await fs.writeFile(path.join(b,'work/reinforce_xlsx_qa_r06.json'),JSON.stringify({all36_cases_match_Python:true,mass_deflection_weld_stress_match:true,angle1_2_and_E_and_weld_leg_recalculated:true,missing_E_handled:true,restored:true,engine:'Artifact Tool; Microsoft Excel not tested'},null,2));
for(const [s,r,n]of [[v,'A2:F26','variant'],[v,'A29:F36','heights'],[c,'A2:H23','comparison1'],[c,'A24:H43','comparison2'],[i,'A2:D23','inputs1'],[i,'A24:D44','inputs2']]){const blob=await wb.render({sheetName:s.name,range:r,scale:1.1,format:'png'});await fs.writeFile(path.join(b,`work/r06_${n}_qa.png`),new Uint8Array(await blob.arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(wb)).save(path.join(b,'outputs/Ленточный_транспортер/02_Расчеты/ЛТ500_Расчёт_усиления_R06.xlsx'));console.log('R06 workbook checks passed');
