import fs from 'node:fs/promises';import path from 'node:path';import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const b='C:/Users/adm/Documents/Codex/2026-10-04/new-chat-2',d=JSON.parse(await fs.readFile(path.join(b,'work/seat_r05.json'),'utf8')),wb=Workbook.create(),c=wb.worksheets.add('Седла'),i=wb.worksheets.add('Параметры');
function style(s,r,w){s.showGridLines=false;s.getRange(r).format.font={name:'Arial',size:11,color:'#202A33'};s.getRange(r).format.rowHeight=35;s.getRange(r).format.verticalAlignment='center';w.forEach((n,j)=>s.getRange(`${String.fromCharCode(65+j)}:${String.fromCharCode(65+j)}`).format.columnWidth=n);s.getRange('A2').format.font={name:'Arial',size:15,bold:true};}
function head(s,r){s.getRange(r).format.fill='#263C52';s.getRange(r).format.font={name:'Arial',size:11,bold:true,color:'#FFFFFF'};s.getRange(r).format.wrapText=true;s.getRange(r).format.rowHeight=48;}
function note(s,r,t){s.getRange(r).merge();s.getRange(r.split(':')[0]).values=[[t]];s.getRange(r).format.wrapText=true;s.getRange(r).format.rowHeight=58;}
style(i,'A1:D35',[48,23,15,92]);i.getRange('A2').values=[['Параметры наклонного опирания R05']];i.getRange('A5:D5').values=[['Параметр','Значение','Единица','Основание / статус']];head(i,'A5:D5');
const p=[['E',200000,'МПа','Допущение упругого расчёта'],['Плотность',7850,'кг/м³','Справочное значение'],['g',9.80665,'м/с²','Константа'],['Условная огибающая опоры R04',d.load_from_R04_N,'Н','q + трубы + местные 15 кг; не полный расчёт, возможен двойной учёт'],['Текущий уклон',1.5,'град','Временный вариант в диапазоне 1–2°'],['Максимальный уклон',2,'град','Для скатывающей составляющей'],['Минимальная толщина выбранного седла',10,'мм','Кандидат по локальной жёсткости, не утверждённое сечение'],['Длина седла',100,'мм','Габарит вдоль транспортёра'],['Ширина седла',60,'мм','Площадка над трубой'],['Наружная ширина рельса',50,'мм','Труба R03 100×50×3'],['Наружный радиус рельса',6,'мм','Номинальное допущение сечения R03'],['Ширина верхней трубы',100,'мм','Вдоль транспортёра, труба R04 80×100×4'],['Наружный радиус верхней трубы',8,'мм','Номинальное допущение R04'],['Толщина верхней стенки',4,'мм','Свойства поставки не проверены'],['Ориентир прогиба седла',.05,'мм','Предлагаемый критерий для отдельной упругой полосы, не норматив'],['Лента по середине',800,'мм','Условный отсчёт высоты, точка не подтверждена'],['Лента — плоскость опирания рельса',170,'мм','Допущение, роликами не подтверждено'],['Стойка R04 без седла',542,'мм','Отрезок модельной стойки, не производственная длина'],['Высота верхней трубы',80,'мм','R04'],['Толщина плиты',8,'мм','Геометрическая заготовка R04'],['Площадь сечения стойки',540.8230016469242,'мм²','Расчёт геометрии R04; размеры труб здесь не изменяются'],['Площадь сечения поперечины',1334.7964473723105,'мм²','Расчёт геометрии R04'],['Площадь сечения рельса',840.8230016469242,'мм²','Расчёт геометрии R03'],['Размер плиты продольный',120,'мм','R04, без расчёта основания'],['Размер плиты поперечный',150,'мм','R04'],['Длина справочного отрезка рельса',300,'мм','Четыре отрезка для узла стыка; не полные модули'],['Длина поперечины',700,'мм','R04'],['Пролёт верхней стенки',null,'мм','Ширина трубы минус две толщины стенок']];
i.getRange('A6:D33').values=p;i.getRange('B33').formulas=[['=B17-2*B19']];i.getRange('A6:D33').format.wrapText=true;i.getRange('A6:D33').format.rowHeight=44;i.getRange('B6:B33').format.fill='#FFF0C2';i.getRange('B33').format.fill='#E9F2EE';
style(c,'A1:H40',[27,24,24,25,25,23,23,28]);c.getRange('A2:H2').merge();c.getRange('A2').values=[['Наклонные седла и местная жёсткость R05']];note(c,'A3:H3','Не для изготовления. Все усилия — частичные условные огибающие. Допускаемые напряжения не назначены, реальный контакт и швы не решены. Массы труб сохранены из R04; CAD фиксирован и не связан с Excel.');
c.getRange('A5:H5').values=[['t min, мм','t центр, мм','t max, мм','Масса одного, кг','P на одно, Н','σ полосы, МПа','δ полосы, мм','δ ≤ ориентир']];head(c,'A5:H5');
for(let n=0;n<3;n++){let r=n+6;c.getRange(`A${r}`).values=[[[6,8,10][n]]];c.getRange(`B${r}:H${r}`).formulas=[[
`=A${r}+'Параметры'!B13/2*TAN('Параметры'!B10*PI()/180)`,`=A${r}+'Параметры'!B13*TAN('Параметры'!B10*PI()/180)`,`='Параметры'!B13*'Параметры'!B14*B${r}*10^-9*'Параметры'!B7`,`='Параметры'!B9+2*D${r}*'Параметры'!B8`,`=6*(E${r}*('Параметры'!B17-2*'Параметры'!B18)/4)/(('Параметры'!B15-2*'Параметры'!B16)*A${r}^2)`,`=IF(OR(ISBLANK('Параметры'!B6),'Параметры'!B6<=0),"нет E",E${r}*('Параметры'!B17-2*'Параметры'!B18)^3/(48*'Параметры'!B6*(('Параметры'!B15-2*'Параметры'!B16)*A${r}^3/12)))`,`=IF(ISNUMBER(G${r}),G${r}<='Параметры'!B20,"не задано")` ]];}
c.getRange('B6:G8').setNumberFormat('0.000');c.getRange('A6:A8').format.fill='#FFF0C2';
const labels=[['t центра выбранного седла','мм','Плоскость опирания рельса сохраняется'],['P выбранного седла','Н','Вся огибающая плюс вес двух седел на одно'],['Плоская ширина рельса','мм','Наружная ширина минус два радиуса'],['Плоская ширина верха трубы','мм','Опорная поверхность уже наружных 100 мм'],['Площадь контакта половины седла','мм²','Номинальная плоскость, не реальное распределение'],['σ верхней стенки — ориентир','МПа','Полоса с опиранием по краям и центральной площадкой'],['δ верхней стенки — ориентир','мм','Не расчёт контакта в Simulation'],['Скатывающая составляющая','Н','Без усилий натяжения ленты; нужна фиксация'],['Длина средней стойки','мм','R04 длина минус толщина седла по центру'],['Объём опоры без рельсов','м³','Семь тел опоры'],['Масса опоры без рельсов','кг','Плотность задана явно'],['Объём 4 справочных рельсов','м³','Четыре коротких отрезка'],['Масса узла с отрезками','кг','Не масса транспортёра']];
labels.forEach((x,n)=>{let r=n+12;c.getRange(`A${r}:C${r}`).merge();c.getRange(`A${r}`).values=[[x[0]]];c.getRange(`E${r}`).values=[[x[1]]];c.getRange(`F${r}:H${r}`).merge();c.getRange(`F${r}`).values=[[x[2]]];});
c.getRange('D12:D24').formulas=[ ["='Параметры'!B12+'Параметры'!B13/2*TAN('Параметры'!B10*PI()/180)"],["='Параметры'!B9+2*'Параметры'!B13*'Параметры'!B14*D12*10^-9*'Параметры'!B7*'Параметры'!B8"],["='Параметры'!B15-2*'Параметры'!B16"],["='Параметры'!B17-2*'Параметры'!B18"],["='Параметры'!B13/2*D14/COS('Параметры'!B10*PI()/180)"],["=6*(D13/'Параметры'!B14*(2*'Параметры'!B33-D15)/8)/'Параметры'!B19^2"],["=IF(OR(ISBLANK('Параметры'!B6),'Параметры'!B6<=0),\"нет E\",D13/'Параметры'!B14*(8*'Параметры'!B33^3-4*'Параметры'!B33*D15^2+D15^3)/(384*'Параметры'!B6*('Параметры'!B19^3/12)))"],["=D13*SIN('Параметры'!B11*PI()/180)"],["='Параметры'!B23-D12"],["=('Параметры'!B27*'Параметры'!B32+2*'Параметры'!B26*D20+2*'Параметры'!B29*'Параметры'!B30*'Параметры'!B25+2*'Параметры'!B13*'Параметры'!B14*D12)*10^-9"],["=D21*'Параметры'!B7"],["=4*'Параметры'!B28*'Параметры'!B31*10^-9"],["=(D21+D23)*'Параметры'!B7"] ];
c.getRange('D12:D24').setNumberFormat('0.000');c.getRange('D21:D21').setNumberFormat('0.000000000');c.getRange('D23:D23').setNumberFormat('0.000000000');c.getRange('A12:H24').format.wrapText=true;c.getRange('A12:H24').format.rowHeight=42;
note(c,'A26:H26','Верхняя стенка трубы даёт большую местную деформацию, чем седло. Одномерные модели служат ориентиром; они не доказывают местную прочность трубы. Скругления, распределение контакта и крепления требуют следующей проверки.');
c.getRange('A29:E29').values=[['Ось, мм','Лента, мм','Опирание рельса, мм','Верх трубы, мм','Стойка, мм']];head(c,'A29:E29');
for(let n=0;n<5;n++){let r=n+30;c.getRange(`A${r}`).values=[[[200,2600,5000,7400,9800][n]]];c.getRange(`B${r}:E${r}`).formulas=[[`='Параметры'!B21+(5000-A${r})*TAN('Параметры'!B10*PI()/180)`,`=B${r}-'Параметры'!B22`,`=C${r}-$D$12`,`=D${r}-'Параметры'!B24-'Параметры'!B25`]];}
c.getRange('A30:E34').setNumberFormat('0.000');note(c,'A36:H36','Геометрический контакт при уклоне решается седлом. В CAD нет фиксаторов седел, швов и зазора стыка. Высоты условны до выбора роликов; окончательные детали, DXF и УП не выпущены.');
wb.recalculate();const tol=1e-6;function near(v,e){if(typeof v!=='number'||Math.abs(v-e)>tol)throw Error(`${v} differs ${e}`);}
for(let n=0;n<3;n++){const r=d.seat_candidates[n],v=c.getRange(`B${n+6}:G${n+6}`).values[0];[r.t_centre_mm,r.t_max_mm,r.volume_one_m3*7850,r.load_one_seat_upper_N,r.seat_strip_sigma_MPa,r.seat_strip_delta_mm].forEach((x,j)=>near(v[j],x));}
near(c.getRange('D17').values[0][0],d.top_wall.sigma_MPa);near(c.getRange('D18').values[0][0],d.top_wall.delta_mm);near(c.getRange('D22').values[0][0],d.variants[1].stand_mass_kg);near(c.getRange('D24').values[0][0],d.variants[1].with_reference_rails_mass_kg);
for(const th of [1,2]){i.getRange('B10').values=[[th]];wb.recalculate();const v=d.variants.find(x=>x.angle_deg===th);near(c.getRange('D22').values[0][0],v.stand_mass_kg);near(c.getRange('E30').values[0][0],v.stations[0].leg_length_mm);}i.getRange('B10').values=[[1.5]];i.getRange('B6').values=[[100000]];wb.recalculate();near(c.getRange('D18').values[0][0],2*d.top_wall.delta_mm);i.getRange('B6').values=[[null]];wb.recalculate();if(c.getRange('D18').values[0][0]!=='нет E'||c.getRange('H8').values[0][0]!=='не задано')throw Error('Missing E');i.getRange('B6').values=[[200000]];wb.recalculate();
const scan=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!',options:{useRegex:true,maxResults:40},maxChars:1000});await fs.writeFile(path.join(b,'work/seat_xlsx_scan_r05.txt'),scan.ndjson);
await fs.writeFile(path.join(b,'work/seat_xlsx_qa_r05.json'),JSON.stringify({independentPythonResultsMatch:true,angle1_2_mass_and_heights_recalculated:true,half_E_and_blank_E_checked:true,restored:true,engine:'Artifact Tool, not Microsoft Excel'},null,2));
for(const [s,r,n]of [[c,'A2:H26','results'],[c,'A29:H36','heights'],[i,'A2:D19','inputs1'],[i,'A20:D33','inputs2']]){const blob=await wb.render({sheetName:s.name,range:r,scale:1.1,format:'png'});await fs.writeFile(path.join(b,`work/r05_${n}_qa.png`),new Uint8Array(await blob.arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(wb)).save(path.join(b,'outputs/Ленточный_транспортер/02_Расчеты/ЛТ500_Расчёт_седел_R05.xlsx'));console.log('R05 workbook checks passed');

