import fs from 'node:fs/promises';import path from 'node:path';import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const base='C:/Users/adm/Documents/Codex/2026-10-04/new-chat-2',dat=JSON.parse(await fs.readFile(path.join(base,'work/support_r04.json'),'utf8')),wb=Workbook.create();
const calc=wb.worksheets.add('Опоры'),inp=wb.worksheets.add('Параметры'),prof=wb.worksheets.add('Сечения');
function style(s,r,widths){s.showGridLines=false;s.getRange(r).format.font={name:'Arial',size:11,color:'#202A33'};s.getRange(r).format.rowHeight=32;s.getRange(r).format.verticalAlignment='center';widths.forEach((w,i)=>s.getRange(`${String.fromCharCode(65+i)}:${String.fromCharCode(65+i)}`).format.columnWidth=w);s.getRange('A2').format.font={name:'Arial',size:15,bold:true};}
function head(s,r){s.getRange(r).format.fill='#263C52';s.getRange(r).format.font={name:'Arial',size:11,bold:true,color:'#FFFFFF'};s.getRange(r).format.wrapText=true;s.getRange(r).format.rowHeight=43;}
function note(s,r,t){s.getRange(r).merge();s.getRange(r.split(':')[0]).values=[[t]];s.getRange(r).format.wrapText=true;s.getRange(r).format.rowHeight=50;}
style(inp,'A1:D26',[46,24,15,88]);inp.getRange('A2').values=[['Параметры опор R04 — не для изготовления']];inp.getRange('A5:D5').values=[['Параметр','Значение','Единица','Основание / статус']];head(inp,'A5:D5');
inp.getRange('A6:D24').values=[
['E',200000,'МПа','Принято для упругого сравнения; конкретный прокат не подтверждён'],['Плотность',7850,'кг/м³','Справочное значение для расчёта массы'],['g',9.80665,'м/с²','Константа'],['Погонная масса материала',30,'кг/м','Первоначальное задание; фактический поток неизвестен'],['Локальный пик одной зоны',15,'кг','Уточнение пользователя: не масса падающей порции'],['Отступ крайних опор',.2,'м','Компоновочное допущение, размеры барабанных узлов открыты'],['Пролёт',null,'м','Вычисляется по полной длине и отступам, четыре равных пролёта'],['Полная длина',10,'м','Уточнённый габарит пользователя'],['Уклон вниз',1.5,'град','Временное значение в диапазоне 1–2°'],['Лента по середине длины',800,'мм','Предложенный отсчёт: высота около 800 мм, точка не подтверждена'],['Лента — верх опоры',170,'мм','Геометрическое допущение; ролики ещё не выбраны'],['Толщина опорной плиты',8,'мм','Заготовка модели, изгиб плиты не рассчитан'],['Расстояние между стойками',600,'мм','Проектный вариант'],['Длина верхней балки',700,'мм','Проектный вариант'],['Размер плиты вдоль движения',120,'мм','Геометрическая заготовка'],['Поперечный размер плиты',150,'мм','Геометрическая заготовка'],['K в формуле Эйлера',2,'—','Отдельная идеальная стойка, не расчёт устойчивости портала'],['Уклон для максимальной стойки',2,'град','Верхняя граница ориентировочного диапазона'],['Масса прочих узлов',null,'кг/м','Пусто: расчёт частичный, лента/ролики/барабаны и прочие узлы исключены']];
inp.getRange('B12').formulas=[['=(B13-2*B11)/4']];inp.getRange('A6:D24').format.wrapText=true;inp.getRange('A6:D24').format.rowHeight=45;inp.getRange('B6:B24').format.fill='#FFF0C2';inp.getRange('B12').format.fill='#E9F2EE';
style(prof,'A1:F27',[43,23,23,23,14,68]);prof.getRange('A2').values=[['Расчётная геометрия труб со скруглениями']];prof.getRange('A5:F5').values=[['Показатель','Рельс','Поперечина','Стойка','Единица','Смысл']];head(prof,'A5:F5');
const labels=[['Обозначение','—','Номинальная геометрия'],['Высота h','мм','Вертикальный размер поперечины / сечения рельса'],['Ширина b','мм','Для поперечины — размер вдоль транспортёра'],['Толщина t','мм','Не проверена по фактической поставке'],['r / t','—','Наружный радиус 2t; не нормативный допуск'],['Наружный радиус','мм','r = 2t'],['Внутренний радиус','мм','r − t'],['Площадь наружная','мм²','Скруглённый прямоугольник'],['Площадь внутренняя','мм²','Пустота'],['Площадь металла','мм²','Разность'],['I наружный','мм⁴','Вертикальный изгиб'],['I пустоты','мм⁴','Вычитаемый момент'],['I вертикальный','мм⁴','Разность'],['W вертикальный','мм³','2I/h'],['Погонная масса','кг/м','Площадь × плотность'],['I горизонтальный','мм⁴','Смена h и b'],['I минимальный','мм⁴','Для отдельной стойки Эйлера']];
for(let i=0;i<labels.length;i++){prof.getRange(`A${i+6}`).values=[[labels[i][0]]];prof.getRange(`E${i+6}:F${i+6}`).values=[[labels[i][1],labels[i][2]]];}
const inertia=(w,h,r)=>`(${w}*${h}^3/12-4*((${h}/2-${r})^2*(1-PI()/4)*${r}^2+(${h}/2-${r})*${r}^3/3+${r}^4*(1/3-PI()/16)))`;
for(const [j,p] of [dat.rail,dat.chosen_crossbeam.section,dat.leg].entries()){
 const c=String.fromCharCode(66+j);prof.getRange(`${c}7:${c}10`).values=[[p.h_mm],[p.b_mm],[p.t_mm],[2]];prof.getRange(`${c}6`).formulas=[[`=${c}7&"×"&${c}8&"×"&${c}9`]];
 prof.getRange(`${c}11:${c}22`).formulas=[ [`=${c}9*${c}10`],[`=${c}11-${c}9`],[`=${c}8*${c}7-(4-PI())*${c}11^2`],[`=(${c}8-2*${c}9)*(${c}7-2*${c}9)-(4-PI())*${c}12^2`],[`=${c}13-${c}14`],[`=${inertia(c+'8',c+'7',c+'11')}`],[`=${inertia('('+c+'8-2*'+c+'9)','('+c+'7-2*'+c+'9)',c+'12')}`],[`=${c}16-${c}17`],[`=2*${c}18/${c}7`],[`=${c}15*'Параметры'!B7*10^-6`],[`=${inertia(c+'7',c+'8',c+'11')}-${inertia('('+c+'7-2*'+c+'9)','('+c+'8-2*'+c+'9)',c+'12')}`],[`=MIN(${c}18,${c}21)`] ];}
prof.getRange('B7:D10').format.fill='#FFF0C2';prof.getRange('A6:F22').format.wrapText=true;prof.getRange('A6:F22').format.rowHeight=39;prof.getRange('B11:D22').setNumberFormat('0.000');note(prof,'A24:F24','Сечения и свойства рассчитываются геометрически; это не паспорт выбранного Ст3. Изменение ячеек Excel не изменяет геометрию фиксированной CAD-модели.');
style(calc,'A1:I40',[20,18,18,20,20,20,23,23,23]);calc.getRange('A2:I2').merge();calc.getRange('A2').values=[['Вертикальные нагрузки и высоты поперечных опор R04']];note(calc,'A3:I3','Схема двух непрерывных двухпролётных модулей, стык шарнирный над общей опорой. Σ=q+трубы+15 кг — условная комбинация, возможен двойной учёт материала. Пять локальных огибающих не действуют одновременно.');
calc.getRange('A5:I5').values=[['Ось, мм','Трубы: длина влияния, м','Материал: длина влияния, м','q, Н','Трубы, Н','Прочие узлы, Н','q + вес, Н','15 кг + вес, Н','Условная Σ, Н']];head(calc,'A5:I5');calc.getRange('A5:I5').format.rowHeight=60;
const factors=[.375,1.25,.75,1.25,.375];for(let i=0;i<5;i++){const r=i+6;calc.getRange(`A${r}:I${r}`).formulas=[[
`=('Параметры'!B11+${i}*'Параметры'!B12)*1000`, `=${factors[i]}*'Параметры'!B12`, `=B${r}${i===0||i===4?"+'Параметры'!B11":""}`, `=C${r}*'Параметры'!B9*'Параметры'!B8`, `=B${r}*2*'Сечения'!B20*'Параметры'!B8`, `=IF(ISBLANK('Параметры'!B24),0,C${r}*'Параметры'!B24*'Параметры'!B8)`, `=SUM(D${r}:F${r})`, `=SUM(E${r}:F${r})+'Параметры'!B10*'Параметры'!B8`, `=G${r}+'Параметры'!B10*'Параметры'!B8` ]];}
calc.getRange('A6:A10').setNumberFormat('0');calc.getRange('B6:I10').setNumberFormat('0.000');
const rows=[['Максимальная вертикальная Σ','Н','Отдельная огибающая опоры'],['Вес верхней балки на единицу длины','Н/м','Для изгиба поперечины'],['Пролёт верхней балки','м','Оси стоек'],['Вес двух крайних свесов','Н','Перенесён в центр для сравнения'],['M верхней балки','Н·м','Вся огибающая в середине'],['σ верхней балки','МПа','Нет допускаемого напряжения'],['δ верхней балки','мм','Только упругий изгиб'],['Максимальная длина стойки','мм','Уклон по Параметры B23'],['N одной стойки','Н','Вся нагрузка на одну стойку + вес верхней балки и стойки'],['σ сжатия стойки','МПа','Нет проверки общей прочности'],['Укорочение стойки','мм','Упругое осевое'],['Идеальная сила Эйлера','Н','Не допускаемая нагрузка портала']];
rows.forEach((x,i)=>{let r=i+13;calc.getRange(`A${r}:C${r}`).merge();calc.getRange(`A${r}`).values=[[x[0]]];calc.getRange(`E${r}`).values=[[x[1]]];calc.getRange(`F${r}:I${r}`).merge();calc.getRange(`F${r}`).values=[[x[2]]];});
calc.getRange('D13:D24').formulas=[ ['=MAX(I6:I10)'],["='Сечения'!C20*'Параметры'!B8"],["='Параметры'!B18/1000"],["=D14*('Параметры'!B19/1000-D15)"],['=(D13+D16)*D15/4+D14*D15^2/8'],["=D17*1000/'Сечения'!C19"],["=IF(OR(ISBLANK('Параметры'!B6),'Параметры'!B6<=0),\"нет E\",((D13+D16)*D15^3/48+5*D14*D15^4/384)*10^9/('Параметры'!B6*'Сечения'!C18))"],["='Параметры'!B15-'Параметры'!B16-'Сечения'!C7-'Параметры'!B17+('Параметры'!B13/2-'Параметры'!B11)*1000*TAN('Параметры'!B23*PI()/180)"],["=D13+'Сечения'!C20*'Параметры'!B19/1000*'Параметры'!B8+'Сечения'!D20*D20/1000*'Параметры'!B8"],["=D21/'Сечения'!D15"],["=IF(OR(ISBLANK('Параметры'!B6),'Параметры'!B6<=0),\"нет E\",D21*D20/('Параметры'!B6*'Сечения'!D15))"],["=IF(OR(ISBLANK('Параметры'!B6),'Параметры'!B6<=0),\"нет E\",PI()^2*'Параметры'!B6*'Сечения'!D22/('Параметры'!B22*D20)^2)"] ];
calc.getRange('D13:D24').setNumberFormat('0.000');calc.getRange('A13:I24').format.wrapText=true;calc.getRange('A13:I24').format.rowHeight=40;
note(calc,'A26:I26','Не включены натяжение ленты, горизонтальные силы, кручение, несовершенства, связи, швы, анкеры и свойства бетона. Размеры плит геометрические. Полная прочность, устойчивость и пригодность к изготовлению НЕ подтверждены.');
calc.getRange('A29:D29').values=[['Ось, мм','Рабочая лента, мм','Верх опоры, мм','Длина стойки, мм']];head(calc,'A29:D29');
for(let i=0;i<5;i++){const r=i+30,s=i+6;calc.getRange(`A${r}:D${r}`).formulas=[[`=A${s}`,`='Параметры'!B15+('Параметры'!B13*1000/2-A${r})*TAN('Параметры'!B14*PI()/180)`,`=B${r}-'Параметры'!B16`,`=C${r}-'Сечения'!C7-'Параметры'!B17`]];}
calc.getRange('A30:D34').setNumberFormat('0.000');note(calc,'A36:I36','Высоты по текущему углу B14, номинальные по осям без поправок на наклонное опирание. На ширине 100 мм при 2° перепад 3,49 мм; требуется наклонная опорная поверхность. Размер лента–опора 170 мм не подтверждён роликами. Не для изготовления.');
wb.recalculate();const tol=1e-6;function near(v,e,s){if(typeof v!=='number'||Math.abs(v-e)>tol)throw Error(`${s}: ${v} vs ${e}`);}
for(let i=0;i<5;i++){const v=calc.getRange(`D${i+6}:I${i+6}`).values[0],r=dat.support_stations[i];[r.R_material_N,r.R_rails_N,0,r.R_uniform_plus_rails_N,r.R_local_plus_rails_N,r.R_conditional_N].forEach((x,j)=>near(v[j],x,'reactions'));const h=calc.getRange(`B${i+30}:D${i+30}`).values[0],ex=dat.height_scenarios[1].stations[i];[ex.belt_mm,ex.stand_top_mm,ex.leg_mm].forEach((x,j)=>near(h[j],x,'heights'));}
near(calc.getRange('D19').values[0][0],dat.chosen_crossbeam.delta_mm,'crossbeam delta');near(calc.getRange('D24').values[0][0],dat.leg_checks.Euler_K2_N,'Euler');near(calc.getRange('D21').values[0][0],dat.leg_checks.load_entire_frame_on_one_leg_N,'leg N');
const orig=calc.getRange('D19').values[0][0];inp.getRange('B6').values=[[100000]];wb.recalculate();near(calc.getRange('D19').values[0][0],2*orig,'half E');inp.getRange('B6').values=[[null]];wb.recalculate();if(calc.getRange('D19').values[0][0]!=='нет E'||calc.getRange('D24').values[0][0]!=='нет E')throw Error('Missing E handling');inp.getRange('B6').values=[[200000]];inp.getRange('B14').values=[[2]];wb.recalculate();near(calc.getRange('D30').values[0][0],dat.height_scenarios[2].stations[0].leg_mm,'angle propagation');inp.getRange('B14').values=[[1.5]];inp.getRange('B24').values=[[10]];wb.recalculate();if(calc.getRange('D19').values[0][0]<=orig)throw Error('extra mass');inp.getRange('B24').values=[[null]];wb.recalculate();near(calc.getRange('D19').values[0][0],orig,'restoration');
const scan=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!',options:{useRegex:true,maxResults:40},maxChars:1000});await fs.writeFile(path.join(base,'work/support_xlsx_scan_r04.txt'),scan.ndjson);
await fs.writeFile(path.join(base,'work/support_xlsx_qa_r04.json'),JSON.stringify({independent_reactions_heights_deflection_Euler_match:true,recalculation_half_E_missing_E_angle_and_extra_mass:true,restored:true,engine:'Artifact Tool; Microsoft Excel not tested'},null,2));
for(const [s,r,n]of [[calc,'A2:I26','loads'],[calc,'A29:I36','heights'],[inp,'A2:D24','inputs'],[prof,'A2:F24','sections']]){const blob=await wb.render({sheetName:s.name,range:r,scale:1.1,format:'png'});await fs.writeFile(path.join(base,`work/r04_${n}_qa.png`),new Uint8Array(await blob.arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(wb)).save(path.join(base,'outputs/Ленточный_транспортер/02_Расчеты/ЛТ500_Расчёт_опор_R04.xlsx'));console.log('R04 workbook checks passed');
