import fs from 'node:fs/promises';import path from 'node:path';import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const b='C:/Users/adm/Documents/Codex/2026-10-04/new-chat-2',d=JSON.parse(await fs.readFile(path.join(b,'work/trough_r10.json'),'utf8')),wb=Workbook.create(),s=wb.worksheets.add('Желоб'),r=wb.worksheets.add('Нагрузки');
function base(s,range,widths){s.showGridLines=false;s.getRange(range).format.font={name:'Arial',size:11,color:'#202A33'};s.getRange(range).format.rowHeight=32;s.getRange(range).format.verticalAlignment='center';widths.forEach((w,j)=>s.getRange(`${String.fromCharCode(65+j)}:${String.fromCharCode(65+j)}`).format.columnWidth=w);s.getRange('A2').format.font={name:'Arial',size:15,bold:true};}
function head(s,rg){s.getRange(rg).format.fill='#263C52';s.getRange(rg).format.font={name:'Arial',size:11,bold:true,color:'#FFFFFF'};s.getRange(rg).format.wrapText=true;s.getRange(rg).format.rowHeight=54;}
function note(s,rg,txt){s.getRange(rg).merge();s.getRange(rg.split(':')[0]).values=[[txt]];s.getRange(rg).format.wrapText=true;s.getRange(rg).format.rowHeight=60;}
const th='$B$23*PI()/180',u=n=>`$B$${n}`,v=n=>`'Желоб'!$B$${n}`;
base(s,'A1:D48',[48,24,18,66]);s.getRange('A2').values=[['Желобчатая лента ЛТ500 · R10']];head(s,'A4:D4');s.getRange('A4:D4').values=[['Результат','Значение','Единица','Основание']];
const rows=[['Нейтральная ширина одного крыла','=(B21-B22)/2','мм','Средняя часть180мм; ширина ленты500'],['Проекция нейтральной ширины',`=B22+2*B5*COS(${th})`,'мм','Не наружный габарит опоры'],['Подъём нейтрального края',`=B5*SIN(${th})`,'мм','От середины профиля'],['Высота верхнего края (локальная)',`=B25+B7+B24/2*(COS(${th})-1)`,'мм','800мм условно до середины; без поправки продольного уклона'],['Площадь до края без горки',`=(B15+(B8-B25)/TAN(${th}))*(B8-B25)/1000000`,'м²','По верхней поверхности идеального профиля'],['Площадь при запасе B29',`=(B15*MAX(0,B8-B25-B29)+MAX(0,B8-B25-B29)^2/TAN(${th}))/1000000`,'м²','Верх материала горизонтален в сечении'],['Плотность для q до края','=B26/B9','кг/м³','Условие q30; без горки и без запаса'],['Грузовместимость с запасом',`=IF(ISBLANK(B27),"нет плотности",B10*B27)`,'кг/м','Реальная плотность не задана'],['Производительность с запасом',`=IF(OR(ISBLANK(B27),ISBLANK(B28)),"нет исходных",3.6*B10*B27*B28)`,'т/ч','Скорость и плотность не выбраны'],['Смещение края внутрь',`=B5*(1-COS(${th}))`,'мм','Нейтральный слой; для перехода'],['Средняя плоская часть сверху',`=B22-B24*TAN(${th}/2)`,'мм','Поправка8мм толщины в идеальных изломах']];
rows.forEach((x,i)=>{let n=i+5;s.getRange(`A${n}:D${n}`).values=[[x[0],null,x[2],x[3]]];s.getRange(`B${n}`).formulas=[[x[1]]];});s.getRange('A5:D15').format.wrapText=true;s.getRange('A5:D15').format.rowHeight=42;s.getRange('B5:B15').setNumberFormat('0.000');s.getRange('B9:B10').setNumberFormat('0.000000');
note(s,'A16:D16','Угол20° — предварительный. При другой толщине/угле нужно перестроить CAD и проверить желобчатость выбранной ленты. Книга не меняет SolidWorks автоматически.');
head(s,'A20:D20');s.getRange('A20:D20').values=[['Исходный параметр','Значение','Единица','Статус']];s.getRange('A21:D35').values=[['Ширина ленты',500,'мм','Подтверждено'],['Средняя часть профиля',180,'мм','Кандидат'],['Угол боковых роликов',20,'град','Кандидат,0<угол<90'],['Толщина ленты',8,'мм','Допущение'],['Высота середины рабочей ленты',800,'мм','Ориентир, точка привязки предположена'],['q материала',30,'кг/м','Ориентир исходного задания'],['Фактическая насыпная плотность',null,'кг/м³','Неизвестна; заполнить после измерения'],['Фактическая скорость',null,'м/с','Не выбрана'],['Запас до края',20,'мм','Сценарий, не подтверждённый критерий'],['Шаг в загрузке',.25,'м','Кандидат'],['Обычный шаг',.75,'м','Кандидат'],['Одна локальная масса',15,'кг','Подтверждено; сочетание с q условно'],['q ленты',5,'кг/м','Допущение'],['Продольный уклон вниз',1.5,'град','Пример из1–2°'],['g',9.80665,'м/с²','Константа']];s.getRange('A21:D35').format.wrapText=true;s.getRange('A21:D35').format.rowHeight=40;s.getRange('B21:B35').format.fill='#FFF0C2';
head(s,'A39:D39');s.getRange('A39:D39').values=[['Длина перехода, мм','ε края: нижняя граница','Статус','Основание']];[500,750,1000,1500].forEach((L,i)=>{let n=i+40;s.getRange(`A${n}:D${n}`).values=[[L,null,'сценарий','Не разрешённое удлинение ленты']];s.getRange(`B${n}`).formulas=[[`=SQRT(1+($B$7^2+$B$14^2)/A${n}^2)-1`]];});s.getRange('B40:B43').setNumberFormat('0.000%');s.getRange('A40:A43').format.fill='#FFF0C2';s.getRange('A40:D43').format.wrapText=true;
note(s,'A45:D45','ε = √(1+(h²+Δz²)/Lt²)−1: только прямолинейная геометрическая нижняя граница. Реальный путь и напряжения зависят от ленты и переходных опор. Резерв750мм требует проверки поставщиком.');note(s,'A47:D47',d.sources[0].url);
base(r,'A1:J29',[34,13,13,13,18,18,18,22,22,22]);r.getRange('A2').values=[['Трёхроликовая опора: условные нагрузки · R10']];r.getRange('A4:B5').values=[['P ленты и материала, Н',null],['Угол желоба, град',null]];r.getRange('B4').formulas=[[`=${v(35)}*COS(${v(34)}*PI()/180)*((${v(26)}+${v(33)})*${v(31)}+${v(32)})`]];r.getRange('B5').formulas=[[`=${v(23)}`]];r.getRange('B4').setNumberFormat('0.000');note(r,'C4:J5','P — статическая нормальная к продольной линии сила на станцию: q30+qB5, шаг750мм, одна15кг порция. Поперечное распределение долей неизвестно. Вес роликов добавлен только в отдельной оценке оси.');
head(r,'A8:J8');r.getRange('A8:J8').values=[['Сценарий долей','β центр','β левое','β правое','A: N центр, Н','A: N левое, Н','A: N правое, Н','A: ΣH поперечная, Н','B: N правое, Н','B: F осевое правое, Н']];
d.load_scenarios.forEach((x,i)=>{let n=i+9;r.getRange(`A${n}:D${n}`).values=[[x.case,...x.vertical_shares]];r.getRange(`E${n}:J${n}`).formulas=[[`=$B$4*B${n}`,`=$B$4*C${n}/COS($B$5*PI()/180)`,`=$B$4*D${n}/COS($B$5*PI()/180)`,`=$B$4*(D${n}-C${n})*TAN($B$5*PI()/180)`,`=$B$4*D${n}*COS($B$5*PI()/180)`,`=$B$4*D${n}*SIN($B$5*PI()/180)`]];});r.getRange('E9:J12').setNumberFormat('0.000');r.getRange('A9:J12').format.rowHeight=45;r.getRange('A9:D12').format.wrapText=true;
note(r,'A14:J14','Модель A: только нормальные контакты; ΣH требует поперечного равновесия ленты. Модель B: вертикальная результирующая раскладывается на нормальную и осевую части. Это две разные модели, их нельзя складывать. Реальное распределение пока не установлено.');
head(r,'A17:D17');r.getRange('A17:D17').values=[['Ось: отдельная крайняя схема','Значение','Единица','Ограничение']];r.getRange('A18:D20').values=[['Вся сила и вес в середине',null,'Н','Макс. N из модели A + вес; без осевой части'],['Напряжение изгиба',null,'МПа','Ось без ослаблений, допускаемое не задано'],['Прогиб',null,'мм','Это не контактная и не ресурсная проверка']];r.getRange('B18:B20').formulas=[[`=MAX(G9:G12)+'Желоб'!$B$35*(B26+B27)`],[`=B18*B24/4*(B23/2)/(PI()*B23^4/64)`],[`=B18*B24^3/(48*B25*(PI()*B23^4/64))`]];r.getRange('B18:B20').setNumberFormat('0.000');r.getRange('A18:D20').format.wrapText=true;r.getRange('A18:D20').format.rowHeight=44;
r.getRange('A23:D27').values=[['Диаметр оси',25,'мм','Кандидат'],['Пролёт опор оси',192,'мм','Новый короткий ролик'],['E',200000,'МПа','Допущение'],['Вращающийся узел с2подшипниками',d.mass_estimate.one_rotating_supported_mass_kg,'кг','Масса геометрического кандидата R10'],['Ось25×200',d.mass_estimate.one_shaft_mass_kg,'кг','Без ступеней/фиксации']];r.getRange('A23:D27').format.wrapText=true;r.getRange('A23:D27').format.rowHeight=44;r.getRange('B23:B27').format.fill='#FFF0C2';r.getRange('B26:B27').setNumberFormat('0.000');note(r,'A29:J29','R08/R09 — история плоской схемы. Натяжение, провис полос желобчатой ленты, трение, ресурс, раму/швы и привод требуется пересчитать. При изменении профиля массы B26/B27 необходимо обновить отдельно.');
for(const n of [17,18,19,20,23,24,25,26,27])r.getRange(`D${n}:J${n}`).merge();head(r,'A17:J17');r.getRange('B9:D12').setNumberFormat('0.000');
function near(x,y){if(typeof x!=='number'||Math.abs(x-y)>1e-7)throw Error(`${x} != ${y}`);}
wb.recalculate();let p=d.profiles[0];[p.projected_neutral_width_mm,p.edge_neutral_rise_mm,800+p.edge_working_rise_mm,p.ideal_no_heap_area_m2,p.area_with_20mm_freeboard_m2,p.required_density_for_q30_full_kg_m3].forEach((x,i)=>near(s.getRange(`B${i+6}`).values[0][0],x));d.transition_scenarios.forEach((x,i)=>near(s.getRange(`B${40+i}`).values[0][0],x.edge_fibre_straight_line_lower_bound_strain));d.load_scenarios.forEach((x,i)=>[x.normal_only_N[0],x.normal_only_N[1],x.normal_only_N[2],x.left_right_transverse_N.reduce((a,b)=>a+b),x.vertical_resultant_normal_N[2],x.vertical_resultant_axial_N[2]].forEach((z,j)=>near(r.getRange(`E${9+i}:J${9+i}`).values[0][j],z)));near(r.getRange('B20').values[0][0],d.shaft_screen.shaft_deflection_mm);
if(s.getRange('B12').values[0][0]!=='нет плотности'||s.getRange('B13').values[0][0]!=='нет исходных')throw Error('missing inputs');s.getRange('B27:B28').values=[[1000],[.2]];wb.recalculate();near(s.getRange('B12').values[0][0],p.area_with_20mm_freeboard_m2*1000);near(s.getRange('B13').values[0][0],3.6*p.area_with_20mm_freeboard_m2*1000*.2);s.getRange('B27:B28').values=[[null],[null]];s.getRange('B23').values=[[30]];wb.recalculate();near(s.getRange('B6').values[0][0],d.profiles[1].projected_neutral_width_mm);s.getRange('B23').values=[[20]];s.getRange('B29').values=[[100]];wb.recalculate();near(s.getRange('B10').values[0][0],0);s.getRange('B29').values=[[20]];wb.recalculate();near(r.getRange('B20').values[0][0],d.shaft_screen.shaft_deflection_mm);
await fs.writeFile(path.join(b,'work/trough_xlsx_qa_r10.json'),JSON.stringify({geometry_and_four_transitions_match_Python:true,four_load_models_and_shaft_bound_match_Python:true,missing_density_speed_and_example_values_checked:true,angle30_and_overheight_freeboard_checked:true,inputs_restored:true,engine:'Artifact Tool; Microsoft Excel not tested'},null,2));const scan=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:40},maxChars:1000});await fs.writeFile(path.join(b,'work/trough_xlsx_scan_r10.txt'),scan.ndjson);
for(const [sh,rg,n]of [[s,'A2:D16','profile'],[s,'A20:D35','inputs'],[s,'A39:D47','transition'],[r,'A2:J14','loads'],[r,'A17:J29','shaft']]){let blob=await wb.render({sheetName:sh.name,range:rg,scale:1.1,format:'png'});await fs.writeFile(path.join(b,`work/r10_${n}_qa.png`),new Uint8Array(await blob.arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(wb)).save(path.join(b,'outputs/Ленточный_транспортер/02_Расчеты/ЛТ500_Расчёт_желобчатой_ленты_R10.xlsx'));console.log('R10 workbook verified');
