exec(open('work/test_top_lower_replacement.py',encoding='utf-8-sig').read().split('trial=Path')[0])
backup=base/'snapshots'/'20261004-lower-replacement-before';backup.mkdir(exist_ok=True)
if not (backup/original.name).exists():shutil.copy2(original,backup/original.name)
doc=source
sw.ActivateDoc3(doc.GetTitle,False,2,e)
c=next(c for c in doc.GetComponents(True) if 'Обойма нижняя' in c.GetPathName)
transform=list(c.Transform2.ArrayData)
doc.ClearSelection2(True)
if not c.Select4(False,doc.SelectionManager.CreateSelectData,False):raise RuntimeError('Selection failed')
if not doc.ReplaceComponents2(str(replacement),'',False,0,True):raise RuntimeError('Replacement failed')
doc.ForceRebuild3(False)
c=next(c for c in doc.GetComponents(True) if c.GetPathName==str(replacement))
shift=max(abs(a-b) for a,b in zip(transform,c.Transform2.ArrayData))
print('transform change',shift,'components',len(doc.GetComponents(False)),flush=True)
if shift>1e-7:raise RuntimeError('Position changed')
