from pathlib import Path
base=Path('outputs/Шнек 1 — параметрическая модель').resolve();p=base/'index.html';s=p.read_text(encoding='utf-8')
s=s.replace("['incline','Угол наклона'","['incline','Угол к горизонтали'")
s=s.replace("const reach=68;","const reach=68;const portAngle=90-angle;")
s=s.replace("setSchematicLine('portInTube',inlet.x-reach,inlet.y,inlet.x-9,inlet.y);","setSchematicLine('portInTube',inlet.x,inlet.y-reach,inlet.x,inlet.y-9);")
s=s.replace("setSchematicLine('portInArrow',inlet.x-reach-5,inlet.y,inlet.x-12,inlet.y);","setSchematicLine('portInArrow',inlet.x,inlet.y-reach-5,inlet.x,inlet.y-12);")
s=s.replace("setSchematicLine('portOutTube',outlet.x+9,outlet.y,outlet.x+reach,outlet.y);","setSchematicLine('portOutTube',outlet.x,outlet.y+9,outlet.x,outlet.y+reach);")
s=s.replace("setSchematicLine('portOutArrow',outlet.x+12,outlet.y,outlet.x+reach+5,outlet.y);","setSchematicLine('portOutArrow',outlet.x,outlet.y+12,outlet.x,outlet.y+reach+5);")
s=s.replace("const r=30,mainArc=(point)=>angle<.001?'':`M ${point.x+r} ${point.y} A ${r} ${r} 0 0 0 ${point.x+r*co} ${point.y-r*si}`;", "const r=30,mainArc=(point,out=false)=>`M ${point.x+(out?-1:1)*r*co} ${point.y+(out?1:-1)*r*si} A ${r} ${r} 0 0 0 ${point.x} ${point.y+(out?1:-1)*r}`;")
s=s.replace("mainArc(outlet)","mainArc(outlet,true)")
s=s.replace("Math.max(60,inlet.x-reach/2),inlet.y-18,`ВХОД · ${fmt(angle)}°`", "inlet.x,inlet.y-reach-12,`ВХОД · ${fmt(portAngle)}°`")
s=s.replace("Math.min(720,outlet.x+reach/2),outlet.y-18,`ВЫХОД · ${fmt(angle)}°`", "outlet.x,outlet.y+reach+18,`ВЫХОД · ${fmt(portAngle)}°`")
s=s.replace("fmt(v.incline)+'° к корпусу'", "fmt(90-v.incline)+'° к корпусу'")
s=s.replace("$('dimPortAngle').textContent=fmt(v.incline)+'°'", "$('dimPortAngle').textContent=fmt(90-v.incline)+'°'")
s=s.replace("Допустимый ввод: 0–20°. Текущие 55° нужно изменить перед применением.","Допустимый ввод: 0–20°. Геометрия этой специальной сборки проверяется отдельно.")
s=s.replace("Углы свыше 20° относятся к специальному проекту; 55° сохранены по заданию.","Угол измеряется от горизонтали. По заданию требуется 55°; фактический угол CAD показан в контроле сборки.")
s=s.replace('<div class="section-head" id="gost">','<div class="note warning" style="margin-top:12px"><h3>Задание и фактическая геометрия</h3><p id="designAngleText">Загружается проверка угла…</p></div><div class="section-head" id="gost">')
s=s.replace('<section class="diagnostics"', '<div class="note" style="margin-top:12px"><h3>Проверка изменения параметров</h3><p id="parameterCheckText">Результаты тестов загружаются…</p></div><section class="diagnostics"',1)
s=s.replace("$('assemblyStatus').textContent=issues?'ЕСТЬ ОШИБКИ CAD':'CAD ПРОВЕРЕН';$('assemblyStatus').className=issues?'pill warn':'pill';", "$('assemblyStatus').textContent=issues?'ЕСТЬ ОШИБКИ CAD':data.design_angle_mismatch?'ТРЕБУЕТ ДОРАБОТКИ':'CAD ПРОВЕРЕН';$('assemblyStatus').className=issues||data.design_angle_mismatch?'pill warn':'pill';\n  $('designAngleText').textContent=`Задание: ${fmt(data.target_incline_deg)}° от горизонтали. В сохранённой CAD-модели: ${data.actual_incline_deg===null?'не проверено':fmt(data.actual_incline_deg)+'°'}. ${data.design_angle_mismatch?'Для целевого угла требуется переработка опоры и отверстия под верхний патрубок.':'Угол модели соответствует заданию.'}`;\n  const names={working_length:'Рабочая длина',tube_diameter:'Диаметр трубы',incline:'Угол по интерфейсу во время теста'};\n  $('parameterCheckText').textContent=(data.parameter_checks||[]).map(r=>`${names[r.parameter]}: ${fmt(r.before)} → ${fmt(r.tested)} → ${fmt(r.before)} — ${r.ok?'проверено без ошибок и пересечений':'вариант отклонён, сборка восстановлена'}`).join('. ')+'. Проверены отдельные варианты; полный диапазон размеров не подтверждён.';")
p.write_text(s,encoding='utf-8')
