exec(open('work/efd_project_inspect.py',encoding='utf-8').read().split("print('project'")[0])
f=typed(p.GetFeatures(),'IProjectFeatures')
b=typed(f.CreateFeature(0),'IBoundaryCondition')
b.SetName('CFD Inlet 10 m3h')
b.put_FCType(1)
print('fctype',b.get_FCType())
q=b.GetParameter(18)
print('param',q.GetValue(0.0),'set',q.SetValue(10/3600),'after',q.GetValue(0.0))
name='CFD_крышка_боковая-1/Бобышка-Вытянуть1//Поверхность<2>'
b.AddTopologicalReferenceUUIDAndName('',name)
print('refs',b.GetTopologicalReferencesUUIDsAndNames(None,None))
try:print('added',f.AddUpdateFeature(p,b))
except Exception as e:print('add ERR',repr(e))
try:print('features',[(x.GetName(),x.GetType()) for x in f.GetFeatures2(True,0) or []])
except Exception as e:print('features ERR',repr(e))
