exec(open('work/efd_project_inspect.py',encoding='utf-8').read().split("print('project'")[0])
f=typed(p.GetFeatures(),'IProjectFeatures')
for old in f.GetFeatures2(True,0) or []:print('remove',old.GetName(),f.RemoveFeature(old.GetUUID()),flush=True)
b=typed(f.CreateFeature(0),'IBoundaryCondition');b.SetName('CFD Inlet 10 m3h');b.put_FCType(1);b.GetParameter(18).SetValue(10/3600)
b.AddTopologicalReferenceUUIDAndName('','CFD_inlet_flange_lid-2/Бобышка-Вытянуть1//Поверхность<2>')
print('add start',flush=True)
print('added',f.AddUpdateFeature(p,b),flush=True)
