exec(open('work/efd_project_inspect.py',encoding='utf-8').read().split("print('project'")[0])
f=typed(p.GetFeatures(),'IProjectFeatures')
for b in f.GetFeatures2(True,0) or []:print('remove',b.GetName(),f.RemoveFeature(b.GetUUID()),flush=True)
print('rebuild',p.Rebuild(True,True,True,False,False,False),flush=True)
print('error',p.GetLastRebuildError(),flush=True)
s=typed(p.GetSolver(),'IProjectSolver')
print('mesh',s.CreateMesh(True,False),flush=True)
print('error2',p.GetLastRebuildError(),flush=True)
