exec(open('work/efd_project_inspect.py',encoding='utf-8').read().split("print('project'")[0])
g=typed(p.GetGeneralSettings(),'IGeneralSettings')
print('before',g.GetFluidType())
g.SetFluidType(2)
print('after',g.GetFluidType())
print('rebuild',p.Rebuild(True,True,True,False,False,False))
print('last',p.GetLastRebuildError())
